### PR TITLE
[VL] Enable timestamp and binary type for HLL agg function

### PR DESCRIPTION
**Pull request by zhli1142015**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

UT.

### CODE REVIEW

**Comment by zhli1142015** [comment]
cc @rui-mo  and @PHILO-HE , thanks

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Comment by zhli1142015** [comment]
Looks there is big regression, is that related to this change? I suppose no, is there any known issue. cc @FelixYBW , @rui-mo , @PHILO-HE , @zhouyuan

**Comment by zhztheplayer** [comment]
> Looks there is big regression, is that related to this change? I suppose no, is there any known issue. cc @FelixYBW , @rui-mo , @PHILO-HE , @zhouyuan

Please ignore that at the moment. It's basically caused by some recent changes to CI machine's resource limitation and should not be related to PR's change.

**Pull request merged**
