### PR TITLE
[GLUTEN-7208][VL]fix: loading libvelox.so failed when using static glog

### PR DESCRIPTION
**Pull request by JinHelin404**
## What changes were proposed in this pull request?

(Fixes: \#7208)

### CODE REVIEW

**Comment by JinHelin404** [comment]
@PHILO-HE Hi. Could you please help to review this? [4434]( https://github.com/apache/incubator-gluten/pull/4434) Introduced gluten link glog, which will cause [7208](https://github.com/apache/incubator-gluten/issues/7208).

**Comment by PHILO-HE** [comment]
@JinHelin404, thanks for your pr! According to your change, linking glog is only required when `ENABLE_GLUTEN_VCPKG` is ON. Could you clarify a bit?

**Comment by PHILO-HE** [comment]
> @PHILO-HE thanks for your reviewing! Actually I also want to figure out why glog is linked in your pr [4434](https://github.com/apache/incubator-gluten/pull/4434) . This pr fix issue when vcpkg is on so I put linking glog in the `if(ENABLE_GLUTEN_VCPKG) `conditional statement.

@JinHelin404, I remember linking glog is necessary when debug build is enabled (at least it's true at that code point).

The issue of both statically and dynamically linking can happen when static glog lib is used, regardless of vcpkg is enabled or not (enabling vcpkg definitely makes static glog lib be used). I think we can remove the below check to also hide those conflict symbols when vcpkg is not enabled:
https://github.com/apache/incubator-gluten/blob/main/cpp/core/CMakeLists.txt#L216.

**Comment by JinHelin404** [comment]
> The issue of both statically and dynamically linking can happen when static glog lib is used, regardless of vcpkg is enabled or not (enabling vcpkg definitely makes static glog lib be used). I think we can remove the below check to also hide those conflict symbols when vcpkg is not enabled:

@PHILO-HE Thanks for your advice. I agree that we can always hide these symbols and I have fixed this pr.

**Comment by PHILO-HE** [comment]
@JinHelin404, please fix cmake format issue (you can just apply the patch generated in that failed CI log). BTW, please verify  this patch in your local to ensure it can really fix your encountered issue .

**Review by PHILO-HE — APPROVED** [review]
Thanks for your fix!

**Pull request merged**
