### PR TITLE
[VL] Do not pushdown filters with HUGEINT columns

### PR DESCRIPTION
**Pull request by jiangjiangtian**
For now, in SubstraitToVeloxPlanConverter::constructSubfieldFilters, if the KIND is HUGEINT, we will throw an excepation, which will trigger fallback. But actually, we can just do not pushdown filters with HUGEINT columns.

### CODE REVIEW

**Comment by jiangjiangtian** [comment]
@kecookier

**Comment by gaoyangxiaozhu** [comment]
could you share the details of the exception stack ?

**Comment by jiangjiangtian** [comment]
> could you share the details of the exception stack ?
Sorry, I can't get the detail of exception stack from log, but I get the following log.
`INFO Driver GlutenFallbackReporter: Validation failed for plan: Scan orc xxx, due to: native check failure:native validation failed due to: in ReadRel, constructSubfieldFilters not support for HUGEINT type.`

So I can write some parts of the exception stack:
```
SubstraitToVeloxPlanConverter::constructSubfieldFilters
SubstraitToVeloxPlanConverter::mapToFilters
SubstraitToVeloxPlanConverter::createSubfieldFilters
SubstraitToVeloxPlanConverter::toVeloxPlan
```

**Comment by jiangjiangtian** [comment]
@rui-mo Please review

**Comment by gaoyangxiaozhu** [comment]
> > could you share the details of the exception stack ?
> 
> Sorry, I can't get the detail of exception stack from log, but I get the following log. `INFO Driver GlutenFallbackReporter: Validation failed for plan: Scan orc xxx, due to: native check failure:native validation failed due to: in ReadRel, constructSubfieldFilters not support for HUGEINT type.`
> 
> So I can write some parts of the exception stack:
> 
> ```
> SubstraitToVeloxPlanConverter::constructSubfieldFilters
> SubstraitToVeloxPlanConverter::mapToFilters
> SubstraitToVeloxPlanConverter::createSubfieldFilters
> SubstraitToVeloxPlanConverter::toVeloxPlan
> ```

that's fine. Actually if my understanding is right, with this PR , instead of fallback to vinalia spark due to unsupported type, the filter would be keep in remaining filter and still offload to native part right ?

If yes, then this change is fine with me. The only consider is we would have 2 duplicate check for `hugint` type. once is introduced by this PR. Antoher is here https://github.com/apache/incubator-gluten/blob/main/cpp/velox/substrait/SubstraitToVeloxPlan.cc#L2144-L2146, i would like to keep only one check in this PR and remove the check in line 2144- 2146.

@PHILO-HE / @rui-mo for review and also double check if we still need this check or actually `hugint` type is supported in native and can be removed.

**Comment by kecookier** [comment]
> > > could you share the details of the exception stack ?
> > 
> > 
> > Sorry, I can't get the detail of exception stack from log, but I get the following log. `INFO Driver GlutenFallbackReporter: Validation failed for plan: Scan orc xxx, due to: native check failure:native validation failed due to: in ReadRel, constructSubfieldFilters not support for HUGEINT type.`
> > So I can write some parts of the exception stack:
> > ```
> > SubstraitToVeloxPlanConverter::constructSubfieldFilters
> > SubstraitToVeloxPlanConverter::mapToFilters
> > SubstraitToVeloxPlanConverter::createSubfieldFilters
> > SubstraitToVeloxPlanConverter::toVeloxPlan
> > ```
> 
> that's fine. Actually if my understanding is right, with this PR , instead of fallback to vinalia spark due to unsupported type, the filter would be keep in remaining filter and still offload to native part right ?
> 
> If yes, then this change is fine with me. The only consideration is we would have 2 duplicate check for `hugint` type. one is introduced by this PR. Antoher is here https://github.com/apache/incubator-gluten/blob/main/cpp/velox/substrait/SubstraitToVeloxPlan.cc#L2144-L2146, i would like to keep only one check in this PR and remove the check in line 2144- 2146.
> 
> @PHILO-HE / @rui-mo for review and also double check if we still need this check or actually `hugint` type is supported in native and can be removed.

This PR actually moves the check earlier, and we will remove the previous judgment logic.

**Comment by gaoyangxiaozhu** [comment]
> > > > could you share the details of the exception stack ?
> > > 
> > > 
> > > Sorry, I can't get the detail of exception stack from log, but I get the following log. `INFO Driver GlutenFallbackReporter: Validation failed for plan: Scan orc xxx, due to: native check failure:native validation failed due to: in ReadRel, constructSubfieldFilters not support for HUGEINT type.`
> > > So I can write some parts of the exception stack:
> > > ```
> > > SubstraitToVeloxPlanConverter::constructSubfieldFilters
> > > SubstraitToVeloxPlanConverter::mapToFilters
> > > SubstraitToVeloxPlanConverter::createSubfieldFilters
> > > SubstraitToVeloxPlanConverter::toVeloxPlan
> > > ```
> > 
> > 
> > that's fine. Actually if my understanding is right, with this PR , instead of fallback to vinalia spark due to unsupported type, the filter would be keep in remaining filter and still offload to native part right ?
> > If yes, then this change is fine with me. The only consideration is we would have 2 duplicate check for `hugint` type. one is introduced by this PR. Antoher is here https://github.com/apache/incubator-gluten/blob/main/cpp/velox/substrait/SubstraitToVeloxPlan.cc#L2144-L2146, i would like to keep only one check in this PR and remove the check in line 2144- 2146.
> > @PHILO-HE / @rui-mo for review and also double check if we still need this check or actually `hugint` type is supported in native and can be removed.
> 
> This PR actually moves the check earlier, and we will remove the previous judgment logic.

ok. thanks for clarify, then If there is always a fallback, curious what benefit does the check eailer bring?

**Comment by PHILO-HE** [comment]
@kecookier, @jiangjiangtian, has Velox already supported pushing down HUGEINT filter? I note this pr was merged long time ago: https://github.com/facebookincubator/velox/pull/4484. Please help verify.

**Comment by kecookier** [comment]
> I note this pr was merged long time ago: https://github.com/facebookincubator/velox/pull/4484. Please help verify.

@PHILO-HE  Thanks for the reminder. We'll double-check.

> then If there is always a fallback, curious what benefit does the check eailer bring?

@gaoyangxiaozhu Currently, reading ORC files does not support pushdown for hugeInt. The previous code would cause the Scan operator to fallback. After the modification, the Scan operator will not fallback, and the filter expression for hugeInt will remain in the Filter operator.

**Comment by jiangjiangtian** [comment]
> @kecookier, @jiangjiangtian, has Velox already supported pushing down HUGEINT filter? I note this pr was merged long time ago: [facebookincubator/velox#4484](https://github.com/facebookincubator/velox/pull/4484). Please help verify.

I verify by pushing down the HUGEINT filter, and I get an exception:
```
Caused by: java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Retriable: False
Expression: !scanSpec_->filter()
Context: Split [Hive: viewfs://hadoop-meituan/nn01/warehouse/mart_caterb2b.db/mid_vendor_stock_sku_day/dt=20240710/part-00842-7a101f7f-3170-4518-b8be-b3b0f9cfd264.c000 0 - 27052712] Task Gluten_Stage_0_TID_152
Top-Level Context: Same as context.
Function: read
File: ../../velox/dwio/dwrf/reader/SelectiveDecimalColumnReader.cpp
Line: 114
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorENS1_22CompileTimeEmptyStringEEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  0x0000000000000000
# 4  _ZN8facebook5velox4dwio6common31SelectiveStructColumnReaderBase4readEiN5folly5RangeIPKiEEPKm
# 5  _ZN8facebook5velox4dwio6common31SelectiveStructColumnReaderBase4nextEmRSt10shared_ptrINS0_10BaseVectorEEPKNS2_8MutationE
# 6  _ZN8facebook5velox4dwrf13DwrfRowReader4nextEmRSt10shared_ptrINS0_10BaseVectorEEPKNS0_4dwio6common8MutationE
# 7  _ZN8facebook5velox9connector4hive14HiveDataSource4nextEmRN5folly10SemiFutureINS4_4UnitEEE
# 8  _ZN8facebook5velox4exec9TableScan9getOutputEv
# 9  _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
# 10 _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
# 11 _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
# 12 _ZN6gluten24WholeStageResultIterator4nextEv
# 13 Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 14 0x00007f794d1a3a34
```
and I see the code in velox (SelectiveDecimalReader::read):
```
VELOX_CHECK(!scanSpec_->filter());
```
So selectiveDecimalReader can't have any filters.
Actually, Velox doesn't support pushing down HUGEINT filters.

**Comment by PHILO-HE** [comment]
> > @kecookier, @jiangjiangtian, has Velox already supported pushing down HUGEINT filter? I note this pr was merged long time ago: [facebookincubator/velox#4484](https://github.com/facebookincubator/velox/pull/4484). Please help verify.
> 
> I verify by pushing down the HUGEINT filter, and I get an exception:
> 
> ```
> Caused by: java.lang.RuntimeException: Exception: VeloxRuntimeError
> Error Source: RUNTIME
> Error Code: INVALID_STATE
> Retriable: False
> Expression: !scanSpec_->filter()
> Function: read
> File: ../../velox/dwio/dwrf/reader/SelectiveDecimalColumnReader.cpp
> Line: 114
> Stack trace:
> # 0  _ZN8facebook5velox7process10StackTraceC1Ei
> # 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
> # 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorENS1_22CompileTimeEmptyStringEEEvRKNS1_18VeloxCheckFailArgsET0_
> # 3  0x0000000000000000
> # 4  _ZN8facebook5velox4dwio6common31SelectiveStructColumnReaderBase4readEiN5folly5RangeIPKiEEPKm
> # 5  _ZN8facebook5velox4dwio6common31SelectiveStructColumnReaderBase4nextEmRSt10shared_ptrINS0_10BaseVectorEEPKNS2_8MutationE
> # 6  _ZN8facebook5velox4dwrf13DwrfRowReader4nextEmRSt10shared_ptrINS0_10BaseVectorEEPKNS0_4dwio6common8MutationE
> # 7  _ZN8facebook5velox9connector4hive14HiveDataSource4nextEmRN5folly10SemiFutureINS4_4UnitEEE
> # 8  _ZN8facebook5velox4exec9TableScan9getOutputEv
> # 9  _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
> # 10 _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
> # 11 _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
> # 12 _ZN6gluten24WholeStageResultIterator4nextEv
> # 13 Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeHasNext
> # 14 0x00007f794d1a3a34
> ```
> 
> and I see the code in velox (SelectiveDecimalReader::read):
> 
> ```
> VELOX_CHECK(!scanSpec_->filter());
> ```
> 
> So selectiveDecimalReader can't have any filters. Actually, Velox doesn't support pushing down HUGEINT filters.

@jiangjiangtian, thanks for your feedback. Not sure whether parquet read has issue on HUGEINT filter. cc @rui-mo.

**Comment by PHILO-HE** [comment]
@jiangjiangtian, @kecookier, I'm ok to firstly use the proposed check to block pushing down such filters.

**Review by kecookier — APPROVED** [review]

**Comment by PHILO-HE** [comment]
@jiangjiangtian, @kecookier, could you check whether this pr is relevant? https://github.com/apache/incubator-gluten/pull/5954

**Comment by kecookier** [comment]
@PHILO-HE Thanks, I will check it.

**Comment by kecookier** [comment]
@PHILO-HE Thanks for the reminder. This PR is duplicate with https://github.com/apache/incubator-gluten/pull/5954, which was submitted earlier. We should probably close this PR and continue working with that one.

**Comment by PHILO-HE** [comment]
> @PHILO-HE Thanks for the reminder. This PR is duplicate with #5954, which was submitted earlier. We should probably close this PR and continue working with that one.

@kecookier, @jiangjiangtian, could you help review that pr? Thanks!

**Pull request closed without merging**
