### PR TITLE
[GLUTEN-7727][CORE] Unify the variable name of GlutenConfig with glutenConf

### PR DESCRIPTION
**Pull request by beliefer**
## What changes were proposed in this pull request?

This PR proposes to unify the the variable name of `GlutenConfig` with `glutenConf`.

Fixes: https://github.com/apache/incubator-gluten/issues/7727

## How was this patch tested?

integration tests

### CODE REVIEW

**Comment by Yohahaha** [comment]
please update PR description and add `Fixes: #ISSUE_ID`, so related issue can be closed automatically.

**Review by zhztheplayer — APPROVED** [review]

**Comment by beliefer** [comment]
ping @zhztheplayer cc @Yohahaha @zhouyuan @zzcclp

**Review by Yohahaha — APPROVED** [review]
👍

**Comment by beliefer** [comment]
@zhztheplayer @Yohahaha Thank you!

**Pull request merged**
