### PR TITLE
[Core] Log unknown fallback reason

### PR DESCRIPTION
**Pull request by gaoyangxiaozhu**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

This is a small follow up PR to address comment of https://github.com/apache/incubator-gluten/pull/4731#discussion_r1501967069

@zhztheplayer 

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by gaoyangxiaozhu** [comment]
@zhztheplayer / @PHILO-HE

**Review by PHILO-HE — APPROVED** [review]
LGTM. Thanks!

**Comment by gaoyangxiaozhu** [comment]
@PHILO-HE I see CH always fail but from the log the build successfully without any error, could you help check ?

**Comment by gaoyangxiaozhu** [comment]
> @PHILO-HE I see CH always fail but from the log the build successfully without any error, could you help check ?

Run Gluten Clickhouse CI

**Comment by gaoyangxiaozhu** [comment]
could you help merge ? @PHILO-HE

**Pull request merged**
