### PR TITLE
[CH] Enable more uts in GlutenOrcV1SchemaPruningSuite  

### PR DESCRIPTION
**Pull request by taiyang-li**
## What changes were proposed in this pull request?

Enable more uts in GlutenOrcV1SchemaPruningSuite, after https://github.com/ClickHouse/ClickHouse/pull/59318 is merged.

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by taiyang-li** [comment]
Run Gluten Clickhouse CI

**Comment by taiyang-li** [comment]
@PHILO-HE  could you see why velox core dump happened in the failed CI.  I didn't change any velox codes 

 
image

**Comment by taiyang-li** [comment]
image 

new velox ci failures, cc @PHILO-HE

**Comment by PHILO-HE** [comment]
@taiyang-li, for the core dump issue, please ignore it in your pr. We will track it. For the 2nd missing mvn issue, we have created one pr to fix it, which is expected to be merged soon. Sorry for inconvenience.

**Comment by taiyang-li** [comment]
Run Gluten Clickhouse CI

**Review by zzcclp — APPROVED** [review]
LGTM

**Pull request merged**
