### PR TITLE
[GLUTEN-5414] [VL] Move ArrowFileScanExec class to module backends-velox

### PR DESCRIPTION
**Pull request by jinchengchenghh**
Arrow related class should not be in module gluten-core

### CODE REVIEW

**Comment by zhztheplayer** [comment]
@jinchengchenghh Thanks for keeping improving the code.

My suggestion: Let's see if it's feasible to directly move ArrowFileSourceScanExec into module `backends-velox`.

Then move [this part of code](https://github.com/apache/incubator-gluten/blob/69fa591d48f6e085e2b4059c1588b845d34c5d1f/gluten-core/src/main/scala/org/apache/gluten/extension/columnar/OffloadSingleNode.scala#L300-L307) into a individual physical rule plugged into Gluten through [this API](https://github.com/apache/incubator-gluten/blob/69fa591d48f6e085e2b4059c1588b845d34c5d1f/gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala#L412).

**Comment by jinchengchenghh** [comment]
https://github.com/apache/incubator-gluten/blob/main/gluten-core/src/main/scala/org/apache/gluten/utils/PlanUtil.scala#L53

If I move `ArrowFileSourceScanExec` to backends-velox, here I won't access it

**Comment by jinchengchenghh** [comment]
And the genExtendedColumnarValidationRules may take effect after `add c2r r2c`, so the test failed

**Comment by zhztheplayer** [comment]
> https://github.com/apache/incubator-gluten/blob/main/gluten-core/src/main/scala/org/apache/gluten/utils/PlanUtil.scala#L53
> 
> If I move `ArrowFileSourceScanExec` to backends-velox, here I won't access it

Am I missing something? I assume `ArrowFileSourceScanExec` should return `true` for `#outputNativeColumnarData`?

**Comment by jinchengchenghh** [comment]
Can you help review this one again? Thanks! @zhztheplayer

**Review by zhztheplayer — APPROVED** [review]

**Pull request merged**
