### PR TITLE
[GLUTEN-5307][VL] Fix Potential Overflow Issue in VeloxShuffleWriter Due to Mismatched Data Types of RowNumber

### PR DESCRIPTION
**Pull request by yangzhg**
## What changes were proposed in this pull request?

Fixes: #5307

### CODE REVIEW

**Comment by marin-ma** [comment]
Thanks. Does this cause overflow in real cases? The uint16_t is used on purpose to benefit L2 cache, and is not supposed to cause the overflow with the 32k limitation of the batch size. Please check https://github.com/apache/incubator-gluten/pull/4401#issuecomment-1895360554

**Comment by yangzhg** [comment]
> Thanks. Does this cause overflow in real cases? The uint16_t is used on purpose to benefit L2 cache, and is not supposed to cause the overflow with the 32k limitation of the batch size. Please check [#4401 (comment)](https://github.com/apache/incubator-gluten/pull/4401#issuecomment-1895360554)
> 
> cc: @FelixYBW

Indeed, using uint16_t in this scenario can lead to overflow.   The specific statements and conditions for reproducing this issue have already been outlined in issue #5307, and I will be providing a dataset shortly to further illustrate this point.

**Comment by marin-ma** [comment]
@yangzhg Thanks for your detailed explanation. There are configurations in Gluten to explicitly limit the batch size within 32k https://github.com/marin-ma/gluten/blob/cf391fae10da22d73c451aced5cd05e474e3bccd/shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala#L929-L946, (the configurations are passed to velox QueryContext here https://github.com/apache/incubator-gluten/blob/c60b5d90e0be23430672d732f9d574267b67c06e/cpp/velox/compute/WholeStageResultIterator.cc#L477-L480), and the prerequisites of doing that is we expect the batch size produced by Velox pipeline always <= 32k. If the input batch size doesn't exceed this limitation, there shouldn't be a problem to use uint16_t. 

However, it seems like there are cases that the output from Velox pipeline can exceed the configured batch size. We are not sure if it's an expected case in Velox. Could you help to raise an issue in Velox to illustrate the case you've, that the Hashagg output can exceed the configured batch size? Thanks!

**Comment by yangzhg** [comment]
> @yangzhg Thanks for your detailed explanation. There are configurations in Gluten to explicitly limit the batch size within 32k
> 
> https://github.com/apache/incubator-gluten/blob/c60b5d90e0be23430672d732f9d574267b67c06e/backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala#L478-L487
> 
> , the configurations are passed to velox QueryContext here
> https://github.com/apache/incubator-gluten/blob/c60b5d90e0be23430672d732f9d574267b67c06e/cpp/velox/compute/WholeStageResultIterator.cc#L477-L480
> 
> , and the prerequisites of doing that is we expect the batch size produced by Velox pipeline always <= 32k. If the input batch size doesn't exceed this limitation, there shouldn't be a problem to use uint16_t.
> However, it seems like there are cases that the output from Velox pipeline can exceed the configured batch size. We are not sure if it's an expected case in Velox. Could you help to raise an issue in Velox to illustrate the case you've met, that the Hashagg output can exceed the configured batch size? Thanks!

OK! Just out of curiosity, how much performance improvement can using uint16_t bring compared to uint32_t?

**Comment by FelixYBW** [comment]
> OK! Just out of curiosity, how much performance improvement can using uint16_t bring compared to uint32_t?

It's up to queries and CPU. You may test in your case. Memory latency can be >50x of L2 cache latency. Split operation is top 5 hotspot in our TPCH test.

If batch size is unlimited, it may more hurt Velox pipeline's performance. Velox is vectorized engine, basic policy is that one operator's output is used by following operator's input. So if batch size is too large it will leads to big cache miss and hurt performance. It's why we use 4K rows as default now.

**Comment by marin-ma** [comment]
@yangzhg Sorry that I didn't notice this PR wasn't got merged. There's no performance impact. Thanks for your fix!

**Comment by FelixYBW** [comment]
@yangzhg Did you create an issue in Velox community?

**Pull request merged**
