### PR TITLE
[GLUTEN-7031][CORE] Initialize new module structure gluten-core / gluten-substrait

### PR DESCRIPTION
**Pull request by zhztheplayer**
#7031 

Part of the dependency graph after the change will become

```
gluten-core
  \- gluten-substrait
        |- backends-clickhouse
        \- gluten-data
             \- backends-velox
```

This belongs to the objective supporting mixed backend execution in Gluten.

The PR only initializes the new module structure. Will move more code in subsequent PRs.

### CODE REVIEW

**Comment by zhztheplayer** [comment]
cc @zzcclp @baibaichen 

This removes blockers towards multi-backend support of Gluten

**Comment by baibaichen** [comment]
@zhztheplayer,  I would prefer the follow directory structure

> ```
> gluten-core
>   \- gluten-substrait
>         |- backends-clickhouse
>         \- backends-velox
>              \- velox-data 
> ```

**Comment by lwz9103** [comment]
@zhztheplayer 
Gluten ClickHouse CI is failed due to 
cpp-ch/local-engine/proto/substrait is linked to ../../../gluten-core/src/main/resources/substrait/proto/substrait
related pr :https://github.com/apache/incubator-gluten/commit/6c921513de0f4449bb309c53327fe41d0455077e

Can you help me to fix it.

**Comment by zhztheplayer** [comment]
hi @baibaichen, the final goal is to implement this dep graph

```
gluten-core
  |- gluten-substrait
  |      \- backends-clickhouse
  \- gluten-arrow
```

Then `backends-velox` could inherit from both `gluten-substrait` and `gluten-arrow`. `gluten-data` may be factored out to `gluten-arrow` which will no longer rely on `gluten-substrait`.

**Comment by lwz9103** [comment]
@zhztheplayer 
The good news is that the gluten ch native code has compiled successfully after modifications. However, the Java code is currently failing to compile due to changes in SoftAffinity. When initializing SoftAffinity in MixedAffinitySuite, several modified parameters should be added. Can you help me resolve this issue?

image
image

You can also use the following command locally to test whether the Java code for Gluten CH can compile successfully.
`mvn clean install -DskipTests -Pbackends-clickhouse -Pspark-3.3 -Pspark-ut`

**Comment by zhztheplayer** [comment]
@lwz9103 Thank you for keeping following. Let me update the PR.

**Comment by baibaichen** [comment]
> hi @baibaichen, the final goal is to implement this dep graph
> 
> ```
> gluten-core
>   |- gluten-substrait
>   |      \- backends-clickhouse
>   \- gluten-arrow
> ```
> 
> Then `backends-velox` could inherit from both `gluten-substrait` and `gluten-arrow`. `gluten-data` may be factored out to `gluten-arrow` which will no longer rely on `gluten-substrait`.

which moudle depeends on gluten-arrow?  Does it only used in backends-velox?

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Pull request merged**
