### PR TITLE
[DOC] build arrow first when build Velox separately.

### PR DESCRIPTION
**Pull request by j7nhai**
## What changes were proposed in this pull request?

Should build arrow first when build Velox separately.

## How was this patch tested?

manually

### CODE REVIEW

**Comment by PHILO-HE** [comment]
@j7nhai, could you let me know the build error you meet? I think building velox doesn't require builing arrow must be done firstly.

**Review by Yohahaha — APPROVED** [review]
👍

**Comment by FelixYBW** [comment]
What's the script when you build Velox? Did you apply Gluten's velox patch when you build velox?

**Comment by j7nhai** [comment]
Actually, build Velox script includes building Arrow. The error I encountered before was that the arrow jar was not installed in the system. Maybe it was accidental.

**Pull request closed without merging**
