### PR TITLE
[CI] Narrow down workflow's filter paths

### PR DESCRIPTION
**Pull request by PHILO-HE**

### CODE REVIEW

**Comment by PHILO-HE** [comment]
Hi @lwz9103, could you take a look?

**Comment by PHILO-HE** [comment]
cc @zzcclp

**Comment by zzcclp** [comment]
can it narrow down workflow's filter pather for the gluten celeborn module too ?
gluten celeborn common/gluten celeborn package/gluten celeborn velox for the velox ci and gluten celeborn common/gluten celeborn package/gluten celeborn clickhouse for the ch ci ?

**Comment by PHILO-HE** [comment]
> can it narrow down workflow's filter pather for the gluten celeborn module too ? gluten celeborn common/gluten celeborn package/gluten celeborn velox for the velox ci and gluten celeborn common/gluten celeborn package/gluten celeborn clickhouse for the ch ci ?

@zzcclp, thanks for your suggestion! I just updated the pr, please check again.

**Review by zzcclp — APPROVED** [review]
LGTM

**Pull request merged**
