### PR TITLE
Revert SortShuffleManager changes in ColumnarShuffleManager 

### PR DESCRIPTION
**Pull request by acvictor**
## What changes were proposed in this pull request?

Revert ColumnarShuffleManager changes in https://github.com/apache/incubator-gluten/pull/6022 to mitigate issue #6140

### CODE REVIEW

**Comment by acvictor** [comment]
@zhli1142015 @marin-ma @ulysses-you can you please review this PR? Will working on investigating the regression separately.

**Review by ulysses-you — APPROVED** [review]
it's interesting.. I'm fine to revert it first

**Comment by acvictor** [comment]
> it's interesting.. I'm fine to revert it first

Thanks! I am also puzzled, will keep you updated on any findings.

**Comment by FelixYBW** [comment]
PR6022 caused performance regression in our nightly test.

**Pull request merged**
