### PR TITLE
[Core] minor change for eliminateProjectList

### PR DESCRIPTION
**Pull request by zhli1142015**
## What changes were proposed in this pull request?

`eliminateProjectList` removed the project function, like below:

`HashAggregate(keys=[knownfloatingpointnormalized(normalizenanandzero(f#38)) AS f#38], functions=[partial_count(1)], output=[f#38, count#46L])`
-->
```
+- ^(5) FlushableHashAggregateTransformer(keys=[f#38], functions=[partial_count(1)], output=[f#38, count#46L])
                                  +- ^(5) ProjectExecTransformer [f#38]
```
`knownfloatingpointnormalized(normalizenanandzero` are removed after the transfer. This is found when doing the change https://github.com/facebookincubator/velox/pull/9272, it can be reproduced by the query:
`Seq(0.0f, -0.0f, 0.0f/0.0f, Float.NaN).toDF("f").groupBy("f").count().collect`

### CODE REVIEW

**Comment by zhli1142015** [comment]
cc @liujiayi771 , thanks.

**Comment by liujiayi771** [comment]
@zhli1142015 Thanks for your fix. We should always keep the contents of `expressionMap.values` and append the `child.outputSet`. But the word 'append' denotes additional content, so it seems a bit odd to consider it as content to be retained in your code. And I think the 'append' should be the last parameter of the method.

Perhaps change the function to the below code, using the set difference method of the `AttributeSet` seems to be more concise, and swap the order of all the arguments that call this function.
```scala
protected def eliminateProjectList(
    projectAttributes: Seq[NamedExpression],
    childOutput: AttributeSet): Seq[NamedExpression] = {
  projectAttributes ++ (childOutput -- projectAttributes).toIndexedSeq
    .sortWith(_.exprId.id < _.exprId.id)
}
```

**Comment by zhli1142015** [comment]
> ```scala
> sortWith
> ```

Thanks, I'm ok with the signature change, but should the logic like below?
```
(projectAttributes ++ (childOutput -- projectAttributes).toIndexedSeq)
    .sortWith(_.exprId.id < _.exprId.id)
```

**Comment by liujiayi771** [comment]
@zhli1142015 Yes, I missed a pair of parentheses.

**Review by liujiayi771 — APPROVED** [review]

**Comment by zhli1142015** [comment]
Run Gluten Clickhouse CI

**Pull request merged**
