### PR TITLE
[CORE] Prevent CH backend from referencing arrow-gluten Jars

### PR DESCRIPTION
**Pull request by zhztheplayer**
Related to https://github.com/apache/incubator-gluten/issues/6489

### CODE REVIEW

**Comment by PHILO-HE** [comment]
Curious Spark csv test is not impacted after arrow-gluten is removed. cc @jinchengchenghh

**Review by PHILO-HE — APPROVED** [review]
cc @baibaichen

**Comment by zhztheplayer** [comment]
@baibaichen I'll merge this PR and please help verify whether https://github.com/apache/incubator-gluten/issues/6489 is fixed after then. Thanks.

**Comment by jinchengchenghh** [comment]
arrow-c-dataand other arrow jars are included in gluten-data module, all the arrow dependencies should be removed from gluten-ut module, it is added because @rui-mo reported it is affected intellij load, but in my environment, it can work well without arrows in gluten-it.

**Pull request merged**
