### PR TITLE
Enable debug implicit util to show substrait content when use spark-shell.

### PR DESCRIPTION
**Pull request by j7nhai**
## What changes were proposed in this pull request?

Enable debug implicit util to show substrait content when use spark-shell.

for codegen, spark have a method to show the gen code in spark-shell.

image

This PR enable to have a method to show the whole stage transform content.

image

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by xumingming** [comment]
@j7nhai Sounds interesting! One question: why limit it to WholeStageCodegenTransformer?

**Comment by j7nhai** [comment]
> @j7nhai Sounds interesting! One question: why limit it to WholeStageCodegenTransformer?

WholeStageTransformer is something similar to WSCG, and by refer to object org.apache.spark.sql.execution.QueryExecution.debug in Apache Spark, this PR provided something to show substrait. More debug utils can also be added in future PR.

**Comment by j7nhai** [comment]
Can this be merged? @xumingming

**Comment by PHILO-HE** [comment]
@j7nhai, can we put the proposed code into GlutenImplicits.scala? 

cc @ulysses-you, please take a look.

**Comment by ulysses-you** [comment]
+1 to move to `GlutenImplicits`

**Pull request closed without merging**
