### PR TITLE
[GLUTEN-5123][INFRA]set up java and maven according to os in build_bundle_package.yml

### PR DESCRIPTION
**Pull request by dcoliversun**
## What changes were proposed in this pull request?

Set up java and maven according to os in build_bundle_package.yml

(Fixes: \#5123)

## How was this patch tested?

Pass the build bundle package in github action.

Manual test:  
* centos7: https://github.com/dcoliversun/gluten/actions/runs/8436722430
* ubuntu: https://github.com/dcoliversun/gluten/actions/runs/8438294441
* centos8: https://github.com/dcoliversun/gluten/actions/runs/8439025928

### CODE REVIEW

**Comment by dcoliversun** [comment]
@zhouyuan @wangyum please review this PR if have time

**Review by wangyum — APPROVED** [review]
LGTM

**Comment by zhouyuan** [comment]
Hi @dcoliversun 
This patch seems trying to generate package for each OS, the package built from centos7 should be to work on other platforms as it's using static packaging via vcpkg. 
Can you please to check the centos7 package can work on your case?

thanks,
-yuan

**Comment by zhouyuan** [comment]
The feature itself looks good to me
CC @PHILO-HE

**Comment by dcoliversun** [comment]
@zhouyuan I'm ok to check the centos7 package. I want to make sure I need to test with bundle jar in https://github.com/dcoliversun/gluten/actions/runs/8436722430

**Review by zhouyuan — APPROVED** [review]
👍

**Comment by zhouyuan** [comment]
> @zhouyuan I'm ok to check the centos7 package. I want to make sure I need to test with bundle jar in https://github.com/dcoliversun/gluten/actions/runs/8436722430

Hi @dcoliversun 
Yes, the static package on centos7 should be work on other platforms. There maybe some requirements for glibc versions, but it should be OK for most of the recent releases.


Initially gluten tried to do a package for each platform, with all the dependencies packed into a third-party jar. This is not required in static packaging. You may also noticed in the recent releases there's only one jar file for specific Spark version(which can work on all platformts). In fact we are in the progress to migrate to static packaging. Here's the detail issue 
https://github.com/apache/incubator-gluten/issues/4942

Thanks,
-yuan

**Comment by dcoliversun** [comment]
@zhouyuan Thanks and I think it's very useful for us. In our production environment, we used the `bundle` and `third-lib` jar. I will follow up this feature. If I need to do anything, I will also do it

**Pull request merged**
