### PR TITLE
[GLUTEN-5189][VL] Correct boost lib path

### LINKED ISSUE #5189: Correct boost lib path
### Backend

VL (Velox)

### Bug description

Currently `package.sh` copies `libboost_*` from `/usr/lib/${ARCH}-linux-gnu/`, after upgrading to 1.84.0,  no such file error will occur.

image

Actually it is installed in `/usr/local/lib/`:

image

`install_boost` function in velox specifies `/usr/local` prefix

https://github.com/facebookincubator/velox/blob/2d899d4fedf8977cfc551e5c1cec3ca79273f36a/scripts/setup-ubuntu.sh#L79

more detail log: https://github.com/wForget/kyuubi/actions/runs/8469948686/job/23206490956

### Spark version

None

### Spark configurations

_No response_

### System information

_No response_

### Relevant logs

_No response_

### PR DESCRIPTION
**Pull request by wForget**
## What changes were proposed in this pull request?

closes #5189

### CODE REVIEW

**Comment by PHILO-HE** [comment]
@liujiayi771, could you help check this? Thanks!

**Comment by liujiayi771** [comment]
@PHILO-HE I mainly test on CentOS 8, but I just created a new Ubuntu environment and found that libboost is indeed installed in the `/usr/local/lib` directory. This is confirmed by the build parameters in the `setup-ubuntu.sh` script, which includes the `--prefix=/usr/local`. 

BTW. Do we have tests for the packaging scripts? We need an empty Docker environment to run these scripts to confirm their correctness. Velox has corresponding tests when modifying `setup-xxx.sh`, and Gluten should also include tests for these script modifications.

**Review by liujiayi771 — APPROVED** [review]

**Comment by PHILO-HE** [comment]
> BTW. Do we have tests for the packaging scripts? We need an empty Docker environment to run these scripts to confirm their correctness. Velox has corresponding tests when modifying `setup-xxx.sh`, and Gluten should also include tests for these script modifications.

Hi @liujiayi771, thanks for your confirmation! We have a verification test for `package.sh` in previous CI, but it is not added back in the new CI. As we are encouraging users to build gluten with static link, do you think we still need a test job for this?

**Review by ulysses-you — APPROVED** [review]

**Comment by ulysses-you** [comment]
I think we'd better add package.sh test back. The static link way needs more time to refine, see
https://github.com/apache/incubator-gluten/pull/5033#issuecomment-2024483029

**Comment by PHILO-HE** [comment]
> I think we'd better add package.sh test back. The static link way needs more time to refine, see [#5033 (comment)](https://github.com/apache/incubator-gluten/pull/5033#issuecomment-2024483029)

@liujiayi771, @ulysses-you, OK. I will try to add it back. Thanks!

**Pull request merged**
