### PR TITLE
[VL] Fallback Window operator if there is a mismatch in output type

### PR DESCRIPTION
**Pull request by JkSelf**
## What changes were proposed in this pull request?

Fallback Window operator if there is a mismatch in output types.

## How was this patch tested?

adding new unit test

### CODE REVIEW

**Comment by JkSelf** [comment]
@FelixYBW

**Comment by FelixYBW** [comment]
Is it spark only? if Not is it easy to fix in Velox? Can you open an issue to track in Velox?

Let's merge this until it's fixed in Velox.

**Comment by JkSelf** [comment]
> Is it spark only? if Not is it easy to fix in Velox? Can you open an issue to track in Velox?
> 
> Let's merge this until it's fixed in Velox.

@FelixYBW This is a bug in velox. Fixed in https://github.com/facebookincubator/velox/pull/9818

**Comment by FelixYBW** [comment]
@JkSelf can we merge the PR? since the velox one is merged

**Comment by FelixYBW** [comment]
Oh, looks this one is just a workaround before velox fix. If so, let's close this one.

**Comment by JkSelf** [comment]
@FelixYBW Yes. Will close this PR.

**Pull request closed without merging**
