### PR TITLE
[GLUTEN-6078][CH] Enable mergetree hdfs suite

### PR DESCRIPTION
**Pull request by loneylee**
## What changes were proposed in this pull request?

(Fixes: \#6078)

## How was this patch tested?

Test by ut

### CODE REVIEW

**Comment by loneylee** [comment]
Run Gluten Clickhouse CI

**Comment by loneylee** [comment]
Run Gluten Clickhouse CI

**Comment by loneylee** [comment]
Run Gluten Clickhouse CI

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
