### PR TITLE
[VL] Enable remaining passed 3.5 UT

### PR DESCRIPTION
**Pull request by gaoyangxiaozhu**
## What changes were proposed in this pull request?

@FelixYBW / @zhouyuan / @yma11 I do a global search with keyworkd `disable for spark3.5`,  those 3 uts should be the only remaning UTs not been enabled for spark 3.5 comparing with 3.4, after this PR is merged, all UT with `disabled for spark3.5` should be covered and enabled, except `Hive compatibility check for get_json_object` with is address by this PR https://github.com/apache/incubator-gluten/pull/5467

(Fixes: \#5341)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by gaoyangxiaozhu** [comment]
@zhouyuan / @yma11

**Comment by FelixYBW** [comment]
Thank you! @gaoyangxiaozhu . @yma11 Can you confirm?

**Comment by yma11** [comment]
> Thank you! @gaoyangxiaozhu . @yma11 Can you confirm?

Hi @FelixYBW these are the failures happens in the ones we copied from Spark3.4. The gaps are not filled yet. I will add those suites and list out the failed ones late.

**Comment by gaoyangxiaozhu** [comment]
the CH CI fail with below error:  @zhouyuan / @FelixYBW 

image

**Comment by yma11** [comment]
It's just already fixed. Rebase your PR please.

**Comment by gaoyangxiaozhu** [comment]
@JkSelf

**Comment by gaoyangxiaozhu** [comment]
hey @zhouyuan / @zhli1142015 can you help sign ?

**Comment by gaoyangxiaozhu** [comment]
> hey @zhouyuan / @zhli1142015 / @yma11 can you help sign ?

ping again

**Review by yma11 — APPROVED** [review]

**Pull request merged**
