### PR TITLE
[VL] Adapt setup scripts for the changes in upstream velox

### PR DESCRIPTION
**Pull request by liujiayi771**
## What changes were proposed in this pull request?

Adapt https://github.com/facebookincubator/velox/pull/9198

## How was this patch tested?

Exists CI.

### CODE REVIEW

**Comment by liujiayi771** [comment]
cc @PHILO-HE, thanks.

**Review by PHILO-HE — APPROVED** [review]
Looks nice! Let's merge this pr after today's velox version is updated. Thank!

**Review by zhztheplayer — CHANGES_REQUESTED** [review]
Velox's update won't work without the changes. I am picking them to https://github.com/apache/incubator-gluten/pull/6616. Thank you for taking care of the update.

**Comment by zhztheplayer** [comment]
Incorporated in https://github.com/apache/incubator-gluten/commit/ca49ab9ce13e2c96250446ef6f3deb0539eef801. Thanks @liujiayi771!

**Pull request closed without merging**
