### PR TITLE
[GLUTEN-6834][CORE] Remove unused DDL plan that doesn't correspond to Substrait spec

### PR DESCRIPTION
**Pull request by EpsilonPrime**
## What changes were proposed in this pull request?

This is part of a larger effort to unfork Substrait.

## How was this patch tested?

Tested utilizing the available unit tests.

### CODE REVIEW

**Comment by EpsilonPrime** [comment]
It's worth noting that DDL operations are connected differently in Substrait so that this code would need to be updated before it could be used anyway.

**Comment by zhztheplayer** [comment]
Hi @rui-mo, where did the code come from, do you remember?

**Comment by rui-mo** [comment]
This was introduced by CH backend with https://github.com/apache/incubator-gluten/commit/614543e4f72d0bbf0ab132de181b6f231db63381. cc: @zzcclp

**Review by zhztheplayer — APPROVED** [review]
+1 if the code is unused

**Comment by zhztheplayer** [comment]
@EpsilonPrime 

By the way I still doubt we can unfork Substrait with minimal effort, though it sounds good. Different native accelerators / libraries would have different ways to implement the same logical computation. It's may not be easy to have a single protocol to unify them.

**Comment by FelixYBW** [comment]
> @EpsilonPrime
> 
> By the way I still doubt we can unfork Substrait with minimal effort, though it sounds good. Different native accelerators / libraries would have different ways to implement the same logical computation. It's may not be easy to have a single protocol to unify them at physical level.

we should have the same protocol in long term, substrait should be able to fit all requirements from different frameworks, libraries and accelerators. It's substrait's goal. But now for Gluten it's not urgent.

**Pull request merged**
