### PR TITLE
[DNM] test parquet complex datatype

### PR DESCRIPTION
**Pull request by zhouyuan**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by zhouyuan** [comment]
note 4 unit tests failed
```
char type values should be padded: nested in map value *** FAILED ***
char type values should be padded: nested in both map key and value *** FAILED ***
char type values should be padded: nested in map key *** FAILED ***
 SPARK-18053: ARRAY equality is broken *** FAILED ***
```

**Comment by FelixYBW** [comment]
@yma11 Can you report the issue to Velox thread?

**Comment by yma11** [comment]
> @yma11 Can you report the issue to Velox thread?

Sure. Let me take a look at the root cause first.

**Comment by FelixYBW** [comment]
@yma11 if all spark UT of complex parquet scan passed, let's remove the flag: spark.gluten.sql.complexType.scan.fallback.enabled

From customer side, we already verified the complex type works

**Comment by yma11** [comment]
The previous issue is valid and I proposed a [fix](https://github.com/facebookincubator/velox/issues/10490) in upstream. I will remove the flag once the fix accepted.

**Pull request closed without merging**
