### PR TITLE
[GLUTEN-4973][VL] Upgrade boost version to 1.84.0

### LINKED ISSUE #4973: [VL] Upgrade boost version to 1.84.0
### Description

Since Velox has upgrade boost version from 1.72.0 to 1.84.0 in CentOS 7/8, we need to adapt this change in Gluten.

https://github.com/oap-project/velox/blob/383e12117d0fb232eeac09bc7a1ab0dc7e74ecd8/scripts/setup-centos7.sh#L171
https://github.com/oap-project/velox/blob/383e12117d0fb232eeac09bc7a1ab0dc7e74ecd8/scripts/setup-centos8.sh#L83

### PR DESCRIPTION
**Pull request by liujiayi771**
## What changes were proposed in this pull request?

Fix #4973.

## How was this patch tested?

N/A

### CODE REVIEW

**Review by zhouyuan — APPROVED** [review]

**Comment by boneanxs** [comment]
What abt ubuntu? https://github.com/facebookincubator/velox/pull/8679 also upgrade boost to 1.84

**Comment by zhouyuan** [comment]
the package.sh is outdated for a while, I'm proposing to use static build:
https://github.com/apache/incubator-gluten/issues/4942

**Comment by boneanxs** [comment]
> the package.sh is outdated for a while, I'm proposing to use static build: #4942

Make sense, I also fount fmt version inside velox is at least 9, but in Ubuntu and CentOS which is default 8, it could cause issues if we use dynamic build.

**Comment by PHILO-HE** [comment]
@boneanxs, let's firstly merge this patch to remove blocking issue for https://github.com/apache/incubator-gluten/pull/4965. As yuan said, package.sh will be deprecated and replaced by static build. If urgently needing the fix for ubuntu, let's do that in a separate PR. Thanks!

**Comment by zhouyuan** [comment]
@liujiayi771 thanks for the patch, will follow up on ubuntu and other OS.

Thanks,
-yuan

**Comment by liujiayi771** [comment]
@zhouyuan I can continue adapting Ubuntu and Debian. I encountered debugging issues with Boost in my environment, so I submitted a quick fix.

**Pull request merged**
