### PR TITLE
[GLUTEN-7373][DOC][VL] Add document for profiling gluten with velox

### PR DESCRIPTION
**Pull request by wForget**
## What changes were proposed in this pull request?

Fixes: #7373

## How was this patch tested?

no

### CODE REVIEW

**Comment by FelixYBW** [comment]
Thank you for your input. Can you put an example chart in the doc?

**Comment by FelixYBW** [comment]
Can you change the name to "profile memory consumption of Gluten".

Also you need to build gluten with -g. Like build as relwithdebinfo.

**Comment by wForget** [comment]
> Thank you for your input. Can you put an example chart in the doc?

Sure, I will add it later

> Can you change the name to "profile memory consumption of Gluten".

`gperftools` can also be used as a CPU profiler. Do we still need to change it?

> Also you need to build gluten with -g. Like build as relwithdebinfo.

I'm not sure if this is required. I will update the docs after I try some more and provide a suitable build script example.

**Comment by FelixYBW** [comment]
> `gperftools` can also be used as a CPU profiler. Do we still need to change it?
> 
Yes, let's add another doc about CPU hotspot profile on necessary.

**Comment by wForget** [comment]
> Also you need to build gluten with -g. Like build as relwithdebinfo.

Is `-g` required? Build with release seems to be able to analyze dump files normally.

**Review by FelixYBW — APPROVED** [review]

**Pull request merged**
