### PR TITLE
[VL] Support kurtosis aggregate function

### PR DESCRIPTION
**Pull request by liujiayi771**
## What changes were proposed in this pull request?

Support kurtosis agg function.

## How was this patch tested?

`VeloxAggregateFunctionsSuite.kurtosis`

### CODE REVIEW

**Comment by liujiayi771** [comment]
@rui-mo Could you help review? There is an accuracy issue similar to covariance. I remember we directly removed the corresponding query for covariance in sql file before. Do you think it would be better to directly modify the result?

**Comment by rui-mo** [comment]
@liujiayi771 Thanks for the suggestion. It looks nice to add these checks back.

**Comment by liujiayi771** [comment]
> @liujiayi771 Thanks for the suggestion. It looks nice to add these checks back.

Ok. I will do this in another PR.

**Comment by liujiayi771** [comment]
cc @rui-mo @PHILO-HE. Could you help review again. I have rebased the latest main branch, and all CI tests passed.

**Review by rui-mo — APPROVED** [review]
Looks good, thanks!

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Pull request merged**
