### PR TITLE
[VL] Enable GlutenJsonExpressionsSuite

### PR DESCRIPTION
**Pull request by zhli1142015**
## What changes were proposed in this pull request?

UT.
## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by PHILO-HE** [comment]
@zhli1142015, there are still some limitation or improvement for supporting json function. I will update velox pr.

**Comment by zhli1142015** [comment]
Yes, I noticed some wrong result from `get_json_object` function, the added suite just can repro the case.

**Comment by PHILO-HE** [comment]
@zhli1142015, could you tell me the inconsistent case on your side?

**Comment by zhli1142015** [comment]
sth like below, you can check the UT.
```
'$.store.book' offload to gluten
- $.store.book *** FAILED ***
  Incorrect evaluation: get_json_object(
  {"store":{"fruit":[{"weight":8,"type":"apple"},{"weight":9,"type":"pear"}],
  "basket":[[1,2,{"b":"y","a":"x"}],[3,4],[5,6]],"book":[{"author":"Nigel Rees",
  "title":"Sayings of the Century","category":"reference","price":8.95},
  {"author":"Herman Melville","title":"Moby Dick","category":"fiction","price":8.99,
  "isbn":"0-553-21311-3"},{"author":"J. R. R. Tolkien","title":"The Lord of the Rings",
  "category":"fiction","reader":[{"age":25,"name":"bob"},{"age":26,"name":"jack"}],
  "price":22.99,"isbn":"0-395-19395-8"}],"bicycle":{"price":19.95,"color":"red"}},
  "email":"amy@only_for_json_udf_test.net","owner":"amy","zip code":"94025",
  "fb:testid":"1234"}
  , $.store.book), actual: [{"author":"Nigel Rees",
  "title":"Sayings of the Century","category":"reference","price":8.95},
  {"author":"Herman Melville","title":"Moby Dick","category":"fiction","price":8.99,
  "isbn":"0-553-21311-3"},{"author":"J. R. R. Tolkien","title":"The Lord of the Rings",
  "category":"fiction","reader":[{"age":25,"name":"bob"},{"age":26,"name":"jack"}],
  "price":22.99,"isbn":"0-395-19395-8"}], expected: [{"author":"Nigel Rees","title":"Sayings of the Century","category":"reference","price":8.95},{"author":"Herman Melville","title":"Moby Dick","category":"fiction","price":8.99,"isbn":"0-553-21311-3"},{"author":"J. R. R. Tolkien","title":"The Lord of the Rings","category":"fiction","reader":[{"age":25,"name":"bob"},{"age":26,"name":"jack"}],"price":22.99,"isbn":"0-395-19395-8"}] (GlutenTestsTrait.scala:286)
'$.store.book[0]' offload to gluten
- $.store.book[0] *** FAILED ***
  Incorrect evaluation: get_json_object(
  {"store":{"fruit":[{"weight":8,"type":"apple"},{"weight":9,"type":"pear"}],
  "basket":[[1,2,{"b":"y","a":"x"}],[3,4],[5,6]],"book":[{"author":"Nigel Rees",
  "title":"Sayings of the Century","category":"reference","price":8.95},
  {"author":"Herman Melville","title":"Moby Dick","category":"fiction","price":8.99,
  "isbn":"0-553-21311-3"},{"author":"J. R. R. Tolkien","title":"The Lord of the Rings",
  "category":"fiction","reader":[{"age":25,"name":"bob"},{"age":26,"name":"jack"}],
  "price":22.99,"isbn":"0-395-19395-8"}],"bicycle":{"price":19.95,"color":"red"}},
  "email":"amy@only_for_json_udf_test.net","owner":"amy","zip code":"94025",
  "fb:testid":"1234"}
  , $.store.book[0]), actual: {"author":"Nigel Rees",
  "title":"Sayings of the Century","category":"reference","price":8.95}, expected: {"author":"Nigel Rees","title":"Sayings of the Century","category":"reference","price":8.95} (GlutenTestsTrait.scala:286)
```

**Comment by zhli1142015** [comment]
cc @PHILO-HE , thanks.

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Comment by FelixYBW** [comment]
@PHILO-HE do we have a track PR to list all the json issues?

**Pull request merged**
