### PR TITLE
[GLUTEN-6176][CH] Add tpcds suite from decimal table schema

### PR DESCRIPTION
**Pull request by loneylee**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#6176)

## How was this patch tested?

Test by ut

### CODE REVIEW

**Comment by loneylee** [comment]
Run Gluten Clickhouse CI

**Comment by loneylee** [comment]
Run Gluten Clickhouse CI

**Comment by loneylee** [comment]
Run Gluten Clickhouse CI

**Review by zzcclp — APPROVED** [review]
LGTM

**Pull request merged**
