### PR TITLE
[GLUTEN-6285][VL] Add debian10 vcpkg depends

### PR DESCRIPTION
**Pull request by wenwj0**
## What changes were proposed in this pull request?
Add debian 10 support in vcpkg depends.

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)
#6285 

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by FelixYBW** [comment]
We don't have CI to track this. Would you like to maintain this support?

**Comment by wenwj0** [comment]
> We don't have CI to track this. Would you like to maintain this support?

@FelixYBW Sure, I am willing to do this, please let me know what I need to do.

**Comment by PHILO-HE** [comment]
@wenwj0, this patch has been verified on debian 10, right?

**Comment by wenwj0** [comment]
@PHILO-HE Yes, I have successfully verified this on Debian 10 docker, and deployed it on my cluster.

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Comment by PHILO-HE** [comment]
@wenwj0, please rebase the code. Will merge this patch if no CI failure. Thanks!

**Pull request merged**
