### PR TITLE
[GLUTEN-8229][VL] Don't rewrite collect_list/collect_set in window

### PR DESCRIPTION
**Pull request by zml1206**
## What changes were proposed in this pull request?

(Fixes: \#8229)

### CODE REVIEW

**Comment by zhztheplayer** [comment]
Hi, is the patch ready for review? I assume it may cause window fallback.

**Comment by zml1206** [comment]
> Hi, is the patch ready for review? I assume it may cause window fallback.

It's already for review , I tested locally with VeloxWindowExpressionSuite.test("collect_list / collect_set").

**Comment by zhztheplayer** [comment]
> > Hi, is the patch ready for review? I assume it may cause window fallback.
> 
> It's already for review , I tested locally with VeloxWindowExpressionSuite.test("collect_list / collect_set").

My mistake. Somehow I didn't see the change in [VeloxSparkPlanExecApi.scala](https://github.com/apache/incubator-gluten/pull/8230/files#diff-d0292be62e0079377cfe87dc778d022d50b81a8dc52e191ebc7e1c9839b86fd2). Thanks for the explanation.

**Comment by zhztheplayer** [comment]
Related to https://github.com/apache/incubator-gluten/pull/5655

**Review by zhztheplayer — APPROVED** [review]

**Pull request merged**
