### PR TITLE
[GLUTEN-7807] Transform relation bound attr using the name if attr'exprId not found.

### PR DESCRIPTION
**Pull request by yikf**
## What changes were proposed in this pull request?
fix https://github.com/apache/incubator-gluten/issues/7807. 

## How was this patch tested?
run tpc-ds q5, it work fine.

### CODE REVIEW

**Comment by jackylee-ch** [comment]
cc @zhztheplayer @zhouyuan @PHILO-HE

**Comment by PHILO-HE** [comment]
Internal TPCDS also passes with this patch. cc @zhouyuan

**Review by PHILO-HE — APPROVED** [review]

**Comment by PHILO-HE** [comment]
@leoluan2009

**Comment by leoluan2009** [comment]
Thanks for this fix！

**Review by jackylee-ch — APPROVED** [review]

**Pull request merged**
