### PR TITLE
[VL] Supports register udf with different signatures

### PR DESCRIPTION
**Pull request by marin-ma**
issue #4988

Native side (UDF defination and registration) 

**Before**: Only support specifying function name and return type in `UdfEntry`. **After**: Add 2 fields `numArgs` and `argTypes` to `UdfEntry`. Serialize both return type and arg types during registration from native to JVM.

Java side (Resolving UDF expression) 

**Before**: Create the `UDFExpression` based on the function name with the only supported return type. **After**: Get the registered return type based on function name and argument types. Create the `UDFExpression` based on the function name and registered return type.

### CODE REVIEW

**Comment by liujp** [comment]
so, can this use the variable-length arguments in UDF？

**Comment by marin-ma** [comment]
> so, can this use the variable-length arguments in UDF？

@liujp I'm afraid not. Will try to resolve it in another patch.

**Comment by marin-ma** [comment]
@kecookier @zhouyuan Could you please help to review? Thanks!

**Comment by marin-ma** [comment]
@PHILO-HE Could you help to review? Thanks!

**Review by PHILO-HE — APPROVED** [review]
Thanks for your great work!

**Pull request merged**
