### PR TITLE
[CORE] Enable SortShuffleSuite with ColumnarShuffleManager

### PR DESCRIPTION
**Pull request by acvictor**
## What changes were proposed in this pull request?

Enable Spark's SortShuffleSuite with shuffle manager set to ColumnarShuffleManager to ensure that shuffle is always compatible with existing Spark cases.

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
Added a new test suite.

### CODE REVIEW

**Comment by acvictor** [comment]
@rui-mo @zhli1142015 can you please review?

**Comment by rui-mo** [comment]
Hi @zzcclp, do we need to exclude this suite for CH backend? Thanks.

**Comment by rui-mo** [comment]
@acvictor Could you rebase this PR to try the CH CI again? Thanks.

**Comment by acvictor** [comment]
@rui-mo I think the Clickhouse CI has failed but I'm not sure how to access it. Should I disable the suite for CH?

**Comment by rui-mo** [comment]
@acvictor We provide an account to log into CH CI system at https://github.com/apache/incubator-gluten/blob/main/docs/get-started/ClickHouse.md#new-ci-system.
> name: gluten, password: hN2xX3uQ4m

But I find the failure looks irrelevant to this change. @zzcclp Could you help confirm?

**Comment by zzcclp** [comment]
please help to exclude the GlutenSortShuffleSuite for CH backend first, thanks.

**Comment by acvictor** [comment]
> please help to exclude the GlutenSortShuffleSuite for CH backend first, thanks.

Done. Can you please review?

**Comment by acvictor** [comment]
@zzcclp @rui-mo can you please review? CH CI is passing.

**Review by rui-mo — APPROVED** [review]
Thanks. Will merge after CI passes.

**Pull request merged**
