### PR TITLE
[VL] Update to add centos9 for weekly build

### PR DESCRIPTION
**Pull request by deepashreeraghu**
## What changes were proposed in this pull request?

To add Centos9 also to weekly builds.

## How was this patch tested?

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by deepashreeraghu** [comment]
@PHILO-HE - I have added Centos9. But, I had a question :  I have used gcc-toolset-12 and apache-maven-3.9.7-bin.tar.gz  in my environment while building. Not sure if it will work with other versions too. 
Is there anyway that this gets tested ?

**Comment by PHILO-HE** [comment]
@deepashreeraghu, the modification of velox_weekly.yml can trigger the running of that job. You can check the failure message. If you need to test in local, you can pull a docker image to do the test.

**Comment by deepashreeraghu** [comment]
@PHILO-HE - the build-job went fine with Centos9 too. Please review and let me know.
cc: @majetideepak

**Review by PHILO-HE — APPROVED** [review]
Looks nice! Thanks!

**Pull request merged**
