### PR TITLE
[GLUTEN-1632][CH]Daily Update Clickhouse Version (20240308)

### PR DESCRIPTION
**Pull request by lwz9103**
Auto commit by gluten daily build, please check the build status and merge it if it's green.

### CODE REVIEW

**Comment by lwz9103** [comment]
Run Gluten Clickhouse CI

**Review by baibaichen — APPROVED** [review]
LGTM

**Comment by xingtao1216** [comment]
Run Gluten Clickhouse CI

**Comment by baibaichen** [comment]
We need merge due to fix rebase fialed https://github.com/ClickHouse/ClickHouse/pull/60205

**Pull request merged**
