### PR TITLE
[DNM][VL] test march=native

### PR DESCRIPTION
**Pull request by zhouyuan**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Review by weiting-chen — APPROVED** [review]
Looks good to me.

**Comment by PHILO-HE** [comment]
@zhouyuan, we may also need to below setting.
https://github.com/apache/incubator-gluten/blob/main/cpp/core/CMakeLists.txt#L27

**Comment by FelixYBW** [comment]
we may add build flag to control march. default is native.

**Comment by zhouyuan** [comment]
> we may add build flag to control march. default is native.

+1, will clean up on the build profile(native, avx512, avx2) and send out for review.

**Pull request closed without merging**
