### PR TITLE
[VL] Use MemConfig to replace MemConfigMutable, which makes the code cleaner and may also lead to some performance improvements.

### PR DESCRIPTION
**Pull request by kecookier**
## What changes were proposed in this pull request?
Currently, in the Gluten code, once `velox::core::MemConfigMutable` is initialized, the key-value pairs are not modified anymore. This scenario is better suited for using `velox::core::MemConfig`. `MemConfigMutable` is suitable for scenarios where key-value pairs are modified by multiple threads.

## How was this patch tested?
existed ci

### CODE REVIEW

**Comment by kecookier** [comment]
@zuochunwei @zhztheplayer @Yohahaha Could you help review this?

**Review by Yohahaha — APPROVED** [review]
LGTM, thank you!

**Review by zhztheplayer — APPROVED** [review]

**Comment by kecookier** [comment]
Thanks.

**Pull request merged**
