### PR TITLE
[GLUTEN-5103][VL] Use jvm libhdfs replace c++ libhdfs3

### LINKED ISSUE #5103: [VL] Supporting JVM based libhdfs connector
### Description

Velox hdfs connector is using libhdfs3 which is a C++ based hdfs client.  The libhdfs3 is from HAWQ project and is not maintained anymore. 
In Gluten we used the CK libhdfs3 fork, and added the delegation token support. (https://github.com/oap-project/libhdfs3)
However there are still some feature gaps like encrypted rpc(https://github.com/ClickHouse/ClickHouse/issues/22236), federated cluster

In practice the HDFS team and Spark team is usually separated so it maybe difficult to introduce a new HDFS client.
 Gluten/Velox may also need to support JVM based libhdfs (hadoop default) as the second option, so there's no feature gap in HDFS connections.

### PR DESCRIPTION
**Pull request by JkSelf**
## What changes were proposed in this pull request?

- Use jvm libhdfs to replace c++ libhdfs in https://github.com/facebookincubator/velox/pull/9835.
- Add viewfs support in gluten to resolve the hdfs path from the views path using `FileSystem.resolvePath(viewPath)`

fixes #5103

## How was this patch tested?

Local verification.

### CODE REVIEW

**Comment by PHILO-HE** [comment]
Seems velox-hdfs part needs to be removed from vcpkg.json. And ports/libhdfs3 also needs to be removed.

**Comment by FelixYBW** [comment]
@JkSelf the PR is depending on the Velox PR, right?

**Comment by FelixYBW** [comment]
@JkSelf can you rebase the PR?

**Comment by JkSelf** [comment]
> @JkSelf the PR is depending on the Velox PR, right?

@FelixYBW Yes. Pending https://github.com/facebookincubator/velox/pull/10446 and https://github.com/facebookincubator/velox/pull/9835

**Comment by ArnavBalyan** [comment]
Hi @JkSelf thanks for creating this! We seem to be getting this error when trying to build on latest main after patching the change, just wanted to know if any additional changes should be made? Thanks!

```
CMake Error at velox/CMakeLists.txt:96 (message):
  Library does not exist:
  /home/user/gluten/ep/build-velox/build/velox_ep/_build/release/lib/libvelox.a
Call Stack (most recent call first):
  velox/CMakeLists.txt:242 (import_library)

-- Configuring incomplete, errors occurred!
```

**Comment by ArnavBalyan** [comment]
I see thanks, it seems to be failing silently somewhere before. The buildbundle stops here with the error. I can debug why velox did not build. Can you please point me to the cmake where the `.so` is being built. Will add some logs to see whats happening thanks!

**Comment by zhouyuan** [comment]
@JkSelf can you please help to do a rebase?

**Comment by zhouyuan** [comment]
pending on https://github.com/facebookincubator/velox/pull/9835

**Comment by zhouyuan** [comment]
@GlutenPerfBot benchmark

**Review by PHILO-HE — APPROVED** [review]
Looks good! Should velox branch be changed from your own branch?

**Comment by JkSelf** [comment]
> Looks good! Should velox branch be changed from your own branch?

Yes. Will change to 2024_10_25 branch later. Thanks.

**Comment by FelixYBW** [comment]
With this PR merged, is our default hdfs is libhdfs, instead of libhdfs3, right? Do we still support libhdfs3? or should wait until libhdfs3 support is merged in Velox? Need we modify jenkins tests?

if we support both how to config? Let's have a new PR to document all the changes on necessary.

**Pull request merged**
