### PR TITLE
[GLUTEN-5136][VL] Duplicated output from Spark-to-Velox broadcast relation conversion

### PR DESCRIPTION
**Pull request by zhztheplayer**
https://github.com/apache/incubator-gluten/issues/5136

Will be tested by https://github.com/apache/incubator-gluten/pull/5058. It's probably not a trivial code path and may delay adding dedicated UTs.

### CODE REVIEW

**Comment by zhztheplayer** [comment]
cc @ulysses-you

**Comment by ulysses-you** [comment]
Thank you @zhztheplayer for the quick fix. After this pr if there is no c2r, the duplicate keys issue is still existed right ?

**Comment by zhztheplayer** [comment]
> Thank you @zhztheplayer for the quick fix. After this pr if there is no c2r, the duplicate keys issue is still existed right ?

After the fix is applied we should no longer have any relevant issues on BHJ unless unknown. 

The issue this PR tried to fix only happened when broadcast exchange is fallen back but bhj is not. Which is a corner case for current Gluten, usually they are both fallen back or both not. Thus ideally we shouldn't have this issue in usual bhj processing.

**Comment by ulysses-you** [comment]
I see, thank you for the explaination!

**Pull request merged**
