### PR TITLE
[VL] Enable unix_seconds Spark function

### PR DESCRIPTION
**Pull request by acvictor**
## What changes were proposed in this pull request?

Enabling unix_seconds Spark function.

## How was this patch tested?

Added a UT.

### CODE REVIEW

**Comment by acvictor** [comment]
@PHILO-HE can you please review this? Thank you!

**Comment by PHILO-HE** [comment]
@acvictor, looks good! Please rebase the code and resolve conflict. Thanks!

**Comment by acvictor** [comment]
> @acvictor, looks good! Please rebase the code and resolve conflict. Thanks!

Done, thank you!

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Comment by FelixYBW** [comment]
Looks good. Thank you. 

@PHILO-HE can you update the function number metric

**Comment by PHILO-HE** [comment]
> Looks good. Thank you.
> 
> @PHILO-HE can you update the function number metric

@FelixYBW, Yes, I have recoded this function in internal OneNote. And will update the metric per month.

**Pull request merged**
