### PR TITLE
[VL] Collapse project if scan is fallback and the outer project is cheap or fallback

### PR DESCRIPTION
**Pull request by zml1206**
## What changes were proposed in this pull request?
follow #7124
In `PushDownInputFileExpression`, we will add new project before leaf node and push down input file expression to the
new project, if scan is fallback and the outer project is cheap or fallback, we can collapse project to simplify physical plan.

## How was this patch tested?

UT.

### CODE REVIEW

**Comment by zml1206** [comment]
cc @zhztheplayer Thank you.

**Comment by zhztheplayer** [comment]
Hi @zml1206, why this is done in rule `PushDownInputFileExpression`? Given that we already had individual rules like `CollapseProjectExecTransformer` to collapse projects. Should we have an individual rule for this feature as well?

**Comment by zml1206** [comment]
> Hi @zml1206, why this is done in rule `PushDownInputFileExpression`? 

Because this `Project` is produced by `PushDownInputFileExpression`.

**Review by zhztheplayer — APPROVED** [review]

**Comment by baibaichen** [comment]
@zml1206  @zhztheplayer 

IIUC, the following codes colud be removed, after this pr, right?

```
GlutenWholeStageColumnarRDD::compute()
    // To support input_file_name(). According to semantic we should return
    // the exact file name a row belongs to. However in columnar engine it's
    // not easy to accomplish this. so we return a list of file(part) names
    split match {
      case FirstZippedPartitionsPartition(_, g: GlutenPartition, _) =>
        InputFileBlockHolderProxy.set(g.files.mkString(","))
      case _ =>
        InputFileBlockHolderProxy.unset()
    }
```

**Pull request merged**
