### PR TITLE
[VL] [Core] Spark Input_file_name Support

### PR DESCRIPTION
**Pull request by gaoyangxiaozhu**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: https://github.com/facebookincubator/velox/issues/9957)

## How was this patch tested?

UT and manually test

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by gaoyangxiaozhu** [comment]
@jinchengchenghh please help review, thanks

**Comment by jinchengchenghh** [comment]
Does only parquet scan need this rule? What about CSV? If the parquet scan will fallback by some reasons, such as it contains the complex datatype hat velox cannot support ,can we apply this rule?

**Comment by gaoyangxiaozhu** [comment]
> Does only parquet scan need this rule? What about CSV? If the parquet scan will fallback by some reasons, such as it contains the complex datatype hat velox cannot support ,can we apply this rule?

currently only focus parquet.

And I have a following PR to address `scan fallback` case , a different final rule to inject new project with `input_file_name()` back

**Comment by jinchengchenghh** [comment]
I will try to implement directly call Spark function `eval` in Gluten side to avoid extra c2r and r2c, if you are not urgent, can you wait for this feature? Now it is under design process. 
This PR looks a bit complicated.

**Comment by gaoyangxiaozhu** [comment]
> I will try to implement directly call Spark function `eval` in Gluten side to avoid extra c2r and r2c, if you are not urgent, can you wait for this feature? Now it is under design process. This PR looks a bit complicated.

this PR not introduce extra c2r and r2c, could you explain more context of `eval` and how can it be re-used for `input_file_name` feature ?

**Comment by jinchengchenghh** [comment]
It is just under proposal. When the design is ready, I will ping you.

**Comment by gaoyangxiaozhu** [comment]
> It is just under proposal. When the design is ready, I will ping you.

got! thanks ! FYI, @FelixYBW / @rui-mo ,  the PR is implement per before discussion to convert `input_file_name()` to velox `info column`. But looks your team have new proposal to address the similiar issues (not only input_file_name).  Please let me know if i need to deperate this PR and do new one when @jinchengchenghh 's `eval` is ready.

**Comment by gaoyangxiaozhu** [comment]
ping @rui-mo / @FelixYBW  for above question - do we still need this PR merged with feature flag behind or close it waiting for `eval` ready ?

**Comment by FelixYBW** [comment]
@gaoyangxiaozhu  Let's merge the PR firstly.

**Comment by gaoyangxiaozhu** [comment]
> @gaoyangxiaozhu Let's merge the PR firstly.

thanks confirm, @jinchengchenghh so please help review, I can do a follow PR to cover both `fallback` scenario and also a feature flag to control the behavior :). thank you

**Review by jinchengchenghh — APPROVED** [review]

**Comment by JunhyungSong** [comment]
Why didn't you add this support to Iceberg? Is there any particular reason? @gaoyangxiaozhu

**Pull request merged**
