### PR TITLE
[GLUTEN-7180][CH] Fix ut `Eliminate NAAJ when BuildSide is HashedRelationWithAllNullKeys` for the CH backend when the aqe is on

### LINKED ISSUE #7180: [CH] Fix ut `Eliminate NAAJ when BuildSide is HashedRelationWithAllNullKeys` for the CH backend when the aqe is on
### Backend

CH (ClickHouse)

### Bug description

Fix ut `Eliminate NAAJ when BuildSide is HashedRelationWithAllNullKeys` for the CH backend when the aqe is on

### Spark version

None

### Spark configurations

_No response_

### System information

_No response_

### Relevant logs

_No response_

### PR DESCRIPTION
**Pull request by zzcclp**
## What changes were proposed in this pull request?
Fix ut Eliminate NAAJ when BuildSide is HashedRelationWithAllNullKeys for the CH backend when the aqe is on

Close #7180.
(Fixes: #7180)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by PHILO-HE** [comment]
@zzcclp, we have a pr to fix the velox CI failure: https://github.com/apache/incubator-gluten/pull/7182.

**Comment by zzcclp** [comment]
> @zzcclp, we have a pr to fix the velox CI failure: #7182.

OK, thanks. let it run the CH ci first, I will rebase the latest main after #7182 merged.

**Comment by zzcclp** [comment]
> @zzcclp, we have a pr to fix the velox CI failure: #7182.

already rebased, it passed.

**Review by baibaichen — APPROVED** [review]
LGTM

**Comment by lgbo-ustc** [comment]
LGTM

**Pull request merged**
