### PR TITLE
[GLUTEN-6864][VL] Set a Velox gflag to allow growing buffer created in another Velox task

### PR DESCRIPTION
**Pull request by zhztheplayer**
Rely on Velox rebase https://github.com/apache/incubator-gluten/pull/6928.

Fixes https://github.com/apache/incubator-gluten/issues/6864.

### CODE REVIEW

**Review by zhouyuan — APPROVED** [review]
👍

**Comment by lyy-pineapple** [comment]
@zhztheplayer hi, should this patch be merged into version 1.2.1?

**Comment by zhztheplayer** [comment]
> @zhztheplayer hi, should this patch be merged into version 1.2.1?

Thanks for reminder. This needs to be backported to 1.2.

**Comment by wForget** [comment]
> > @zhztheplayer hi, should this patch be merged into version 1.2.1?
> 
> Thanks for reminder. This needs to be backported to 1.2.

Gluten 1.2.1 seems to miss the fix on velox: https://github.com/facebookincubator/velox/pull/10768

**Pull request merged**
