### PR TITLE
[GLUTEN-7126][VL][1.2] Port #6698 #7525 #7560 for Uniffle bug fix

### PR DESCRIPTION
**Pull request by weiting-chen**
## What changes were proposed in this pull request?

Port #6698 #7525 #7560 to fix Uniffle related bug fix in branch-1.2

## How was this patch tested?

local

### CODE REVIEW

**Comment by PHILO-HE** [comment]
Seem CI failure is related. @SteNicholas, @wForget 

```
 /root/.m2/repository/org/apache/uniffle/rss-client-spark3-shaded/0.8.0/rss-client-spark3-shaded-0.8.0.jar(org/apache/spark/shuffle/RssShuffleManager.class): warning: Cannot find annotation method 'value()' in type 'SuppressFBWarnings': class file for edu.umd.cs.findbugs.annotations.SuppressFBWarnings not found
Error:  /__w/incubator-gluten/incubator-gluten/gluten-uniffle/velox/src/main/java/org/apache/spark/shuffle/writer/VeloxUniffleColumnarShuffleWriter.java:[199,16] error: cannot find symbol
Error:    symbol:   class RssException
Error:    location: class VeloxUniffleColumnarShuffleWriter<K,V>
```

**Comment by PHILO-HE** [comment]
@weiting-chen, the uniffle test fails which should be related.

**Comment by summaryzb** [comment]
@weiting-chen the changes of `gluten-uniffle/velox/src/main/java/org/apache/spark/shuffle/writer/VeloxUniffleColumnarShuffleWriter.java` is made in https://github.com/apache/incubator-gluten/pull/6579 should not be include in this pr. 
cc @PHILO-HE @jackylee-ch

**Comment by weiting-chen** [comment]
@PHILO-HE Please help to review it, thanks.

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Pull request merged**
