### PR TITLE
[GLUTEN-6064][VL] Support loading shared libraries on RedHat-9

### PR DESCRIPTION
**Pull request by deepashreeraghu**
## What changes were proposed in this pull request?
Trying to use the centos-8 based Gluten jar on RHEL9. 

## How was this patch tested?
I have used the centos-8 based Gluten jar on RHEL9 and this is the first step it fails. Once I added this fix, it proceeds well.

### CODE REVIEW

**Comment by deepashreeraghu** [comment]
Created issue for the same - https://github.com/apache/incubator-gluten/issues/6064

**Review by surnaik — APPROVED** [review]

**Comment by deepashreeraghu** [comment]
@surnaik - Thanks for reviewing and approval. 
I see that even after approval this PR is blocked. Please let me know of any pending action from my end ?

**Comment by deepashreeraghu** [comment]
@PHILO-HE - Could you please help here?

**Comment by PHILO-HE** [comment]
> I see that even after approval this PR is blocked. Please let me know of any pending action from my end.

New contributor's first PR needs committer's approval for running CI. Just approved.

@deepashreeraghu, did you test this patch on redhat 9?

**Comment by deepashreeraghu** [comment]
Yes @PHILO-HE. I built Gluten on centos8 and wanted to try it on RHEL9. The first road block I hit into was it was not allowing to proceed due to this condition. After fixing this I was able to proceed and run a simple wordcount on RHEL9 with the jar built on centos8. 
I have not run TPCDS or TPCH yet.

**Review by PHILO-HE — APPROVED** [review]

**Pull request merged**
