### PR TITLE
[VL] Re-enable some failed CI jobs

### PR DESCRIPTION
**Pull request by zhztheplayer**
This is a follow-up to https://github.com/apache/incubator-gluten/pull/4936

### CODE REVIEW

**Comment by zhztheplayer** [comment]
Should wait for https://github.com/facebookincubator/velox/pull/9334 to be merged

**Comment by zhztheplayer** [comment]
@JkSelf

**Review by JkSelf — APPROVED** [review]
LGTM. Thanks.

**Comment by zhztheplayer** [comment]
Note: Join post-spill is still not working as expected so a Q95 case is still disabled, although the regression was fixed byhttps://github.com/facebookincubator/velox/pull/9334

**Pull request merged**
