### PR TITLE
[VL] Support building arrow CPP and finding installed arrow libs from system

### PR DESCRIPTION
**Pull request by PHILO-HE**
## What changes were proposed in this pull request?

This is a part of work to let Gluten/Velox use installed arrow libraries instead of always
building from source, which is for simplifying Gluten/Velox build and saving CI time.

We also have a velox PR to let velox find and use the installed arrow libraries: https://github.com/facebookincubator/velox/pull/9992.

## How was this patch tested?

CI.

### CODE REVIEW

**Review by zhouyuan — APPROVED** [review]

**Comment by jinchengchenghh** [comment]
Please also update the document, thanks!

**Comment by PHILO-HE** [comment]
> Please also update the document, thanks!

@jinchengchenghh, I will do that. Thanks!

**Comment by jinchengchenghh** [comment]
And we don't need to add arrow patch here https://github.com/apache/incubator-gluten/blob/main/ep/build-velox/src/get_velox.sh#L249

**Comment by PHILO-HE** [comment]
> And we don't need to add arrow patch here https://github.com/apache/incubator-gluten/blob/main/ep/build-velox/src/get_velox.sh#L249

@jinchengchenghh, you mean we don't need this patch here or don't need to use git to add it? The git add may be still useful for checking ep cache I guess.

**Pull request merged**
