### PR TITLE
[CORE] Bump celeborn to 0.5.2

### PR DESCRIPTION
**Pull request by yikf**
## What changes were proposed in this pull request?
Bump celeborn to 0.5.2 from 0.5.1

## How was this patch tested?
GA

### CODE REVIEW

**Comment by yikf** [comment]
cc @SteNicholas

**Comment by zhztheplayer** [comment]
@yikf

Any reason for the downgrading? Let's add the information to PR description so future developers could track easier.

**Comment by yikf** [comment]
Hi, @zhouyuan , CI failure appears to be due to S3 not having the Celeborn-0.5.2 package. Does the maintainer need he l pto upload it?
image

**Comment by zhouyuan** [comment]
> Hi, @zhouyuan,
> 
> CI failure appears to be due to S3 not having the Celeborn-0.5.2 package. Does the maintainer need help to upload it? image

Hi @baibaichen @zzcclp 
Could you help to upgrade the Celeborn-0.5.2 package?

thanks,
-yuan

**Comment by yikf** [comment]
friendly ping @baibaichen @zzcclp Please help upgrade the Celeborn-0.5.2 package if you have a time, link https://celeborn.apache.org/download/

**Comment by zhouyuan** [comment]
Hi @lwz9103 can you please help to update the celeborn package used in CK jenkins? 

Thanks, -yuan

**Comment by lwz9103** [comment]
@yikf @zhouyuan 
Due to slow download speeds from the original source, it has been uploaded to S3. The current version (0.5.2) is now available there. In the future, support for downloading from the original source will be added.

**Comment by lwz9103** [comment]
Run Gluten Clickhouse CI on x86

**Comment by yikf** [comment]
@lwz9103 Thanks!

**Review by jackylee-ch — APPROVED** [review]

**Pull request merged**
