### PR TITLE
[GLUTEN-7534][CH] Refactor logics about jit settings

### PR DESCRIPTION
**Pull request by taiyang-li**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#7534)

## How was this patch tested?

Old uts

### CODE REVIEW

**Comment by baibaichen** [comment]
@taiyang-li

Good catch!  We need test performance with this PR .

**Comment by baibaichen** [comment]
Related with https://github.com/ClickHouse/ClickHouse/pull/70598

**Comment by baibaichen** [comment]
`GlutenDataFrameAggregateSuite.count_if` failed with endless loop, after https://github.com/ClickHouse/ClickHouse/pull/70598
781e06bf7fa4836b405d29fae2180b06

**Review by baibaichen — CHANGES_REQUESTED** [review]
fix endless loop for count_if

**Comment by taiyang-li** [comment]
duplicated with  https://github.com/apache/incubator-gluten/pull/8105, close it.

**Pull request closed without merging**
