### PR TITLE
[CORE] Bump scalawarts version to prepare for Scala 2.13 support

### PR DESCRIPTION
**Pull request by zhztheplayer**
1. Bump scalawarts version to prepare for Scala 2.13 support
2. Fix missing case-class inheritance check for shim layer code
3. Minor fixes for gluten-it

### CODE REVIEW

**Comment by zhztheplayer** [comment]
@zzcclp This PR should make scalawarts work for 2.13

**Comment by lwz9103** [comment]
Run Gluten Clickhouse CI

**Comment by zzcclp** [comment]
With this pr, compile with command `mvn clean package -Pbackends-clickhouse -Phadoop-3.3 -Pspark-3.5 -Pscala-2.13 -Pceleborn -Dhadoop.version=3.3.1 -DskipTests -Dcheckstyle.skip`, it causes the below error:
```
[ERROR] error: bad option: -P:wartremover:traverser:io.github.zhztheplayer.scalawarts.InheritFromCaseClass
```

**Comment by zhztheplayer** [comment]
> With this pr, compile with command `mvn clean package -Pbackends-clickhouse -Phadoop-3.3 -Pspark-3.5 -Pscala-2.13 -Pceleborn -Dhadoop.version=3.3.1 -DskipTests -Dcheckstyle.skip`, it causes the below error:
> 
> ```
> [ERROR] error: bad option: -P:wartremover:traverser:io.github.zhztheplayer.scalawarts.InheritFromCaseClass
> ```
> 
> remove `wartremover:traverser:io.github.zhztheplayer.scalawarts.InheritFromCaseClass` from pom.xml, it works fine.

Which PR are you using to add 2.13 support? Or it's a internal mission?

**Comment by zzcclp** [comment]
> > With this pr, compile with command `mvn clean package -Pbackends-clickhouse -Phadoop-3.3 -Pspark-3.5 -Pscala-2.13 -Pceleborn -Dhadoop.version=3.3.1 -DskipTests -Dcheckstyle.skip`, it causes the below error:
> > ```
> > [ERROR] error: bad option: -P:wartremover:traverser:io.github.zhztheplayer.scalawarts.InheritFromCaseClass
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > remove `wartremover:traverser:io.github.zhztheplayer.scalawarts.InheritFromCaseClass` from pom.xml, it works fine.
> 
> Which PR are you using to add 2.13 support? Or it's a internal mission?



> > With this pr, compile with command `mvn clean package -Pbackends-clickhouse -Phadoop-3.3 -Pspark-3.5 -Pscala-2.13 -Pceleborn -Dhadoop.version=3.3.1 -DskipTests -Dcheckstyle.skip`, it causes the below error:
> > ```
> > [ERROR] error: bad option: -P:wartremover:traverser:io.github.zhztheplayer.scalawarts.InheritFromCaseClass
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > remove `wartremover:traverser:io.github.zhztheplayer.scalawarts.InheritFromCaseClass` from pom.xml, it works fine.
> 
> Which PR are you using to add 2.13 support? Or it's a internal mission?

It's in my repo: https://github.com/zzcclp/gluten/tree/support_spark35_scala213, you can try it.

**Comment by lwz9103** [comment]
Run Gluten Clickhouse CI

**Comment by zhztheplayer** [comment]
> > > With this pr, compile with command `mvn clean package -Pbackends-clickhouse -Phadoop-3.3 -Pspark-3.5 -Pscala-2.13 -Pceleborn -Dhadoop.version=3.3.1 -DskipTests -Dcheckstyle.skip`, it causes the below error:
> > > ```
> > > [ERROR] error: bad option: -P:wartremover:traverser:io.github.zhztheplayer.scalawarts.InheritFromCaseClass
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > remove `wartremover:traverser:io.github.zhztheplayer.scalawarts.InheritFromCaseClass` from pom.xml, it works fine.
> > 
> > 
> > Which PR are you using to add 2.13 support? Or it's a internal mission?
> 
> > > With this pr, compile with command `mvn clean package -Pbackends-clickhouse -Phadoop-3.3 -Pspark-3.5 -Pscala-2.13 -Pceleborn -Dhadoop.version=3.3.1 -DskipTests -Dcheckstyle.skip`, it causes the below error:
> > > ```
> > > [ERROR] error: bad option: -P:wartremover:traverser:io.github.zhztheplayer.scalawarts.InheritFromCaseClass
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > remove `wartremover:traverser:io.github.zhztheplayer.scalawarts.InheritFromCaseClass` from pom.xml, it works fine.
> > 
> > 
> > Which PR are you using to add 2.13 support? Or it's a internal mission?
> 
> It's in my repo: https://github.com/zzcclp/gluten/tree/support_spark35_scala213, you can try it.

@zzcclp I've opened https://github.com/zzcclp/gluten/pull/4 which should get things work.

**Review by zzcclp — APPROVED** [review]
LGTM

**Pull request merged**
