### PR TITLE
[VL] Add metric to indicate aggregation pushdown

### PR DESCRIPTION
**Pull request by zhli1142015**
## What changes were proposed in this pull request?

Related Velox code:
https://github.com/facebookincubator/velox/blob/main/velox/vector/LazyVector.cpp#L72

## How was this patch tested?

image

### CODE REVIEW

**Comment by zhli1142015** [comment]
cc @rui-mo  and @PHILO-HE , thanks

**Comment by FelixYBW** [comment]
what does it count?

**Comment by zhli1142015** [comment]
> what does it count?

Lazy loaded values, it's value equals agg function counts * row size.
https://github.com/facebookincubator/velox/blob/main/velox/vector/LazyVector.cpp#L72

**Review by rui-mo — APPROVED** [review]
Thanks.

**Pull request merged**
