### PR TITLE
[GLUTEN-6882][CORE] Move Spark / columnar rule list to backend code

### PR DESCRIPTION
**Pull request by zhztheplayer**
Issue #6882, part of #6853.

The patch removes planner rule customization APIs from `SparkPlanExecApi`, and adds a new API `RuleApi` to allow backends inject their own rule list through a given `RuleInjector`. After the change, backends will maintain their own complete rule lists so more flexibilities will be gained to developers.

Change list:

- Remove following APIs in `SparkPlanExecApi`:
  - genExtendedDataSourceV2Strategies
  - genExtendedQueryStagePrepRules
  - genExtendedAnalyzers
  - genExtendedOptimizers
  - genExtendedStrategies
  - genExtendedColumnarValidationRules
  - genExtendedColumnarTransformRules
  - genExtendedColumnarPostRules
  - genInjectPostHocResolutionRules
  - genInjectExtendedParser
  - genInjectedFunctions
 - Add API trait `RuleApi`, implemented with `CHRuleApi` / `VeloxRuleApi`.
 - Add `RuleInjector` which is passed to backends through `RuleApi` from Gluten core. By which backends could inject their own rule lists to Spark and Gluten.

### CODE REVIEW

**Comment by zhztheplayer** [comment]
cc @zhanglistar @baibaichen

**Review by PHILO-HE — COMMENTED** [review]
Seems CH backend CI is not trigged. cc @baibaichen

**Comment by zhztheplayer** [comment]
Run Gluten Clickhouse CI

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Pull request merged**
