### PR TITLE
[UT] Remove isVeloxBackendLoaded usage from file metadata UT

### PR DESCRIPTION
**Pull request by gaoyangxiaozhu**
## What changes were proposed in this pull request?

As we claim the `isxxBackendLoaded` usage should be better avoid, and will be remove when time ripe.
I didn't notice that when adding this part ut before.

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by gaoyangxiaozhu** [comment]
@PHILO-HE / @rui-mo  help review

**Comment by gaoyangxiaozhu** [comment]
@PHILO-HE  the CH fail could you help re-trigger only CH run ?

**Comment by PHILO-HE** [comment]
> @PHILO-HE the CH fail could you help re-trigger only CH run ?

@gaoyangxiaozhu, just triggered. We can leave a comment "Run Gluten Clickhouse CI" to trigger CH CI.

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Comment by gaoyangxiaozhu** [comment]
@PHILO-HE could you help merge ?

**Pull request merged**
