### PR TITLE
[VL] Support jemalloc memory allocator

### PR DESCRIPTION
**Pull request by wForget**
## What changes were proposed in this pull request?

As commented in https://github.com/apache/incubator-gluten/issues/7397#issuecomment-2408427286, I experienced RSS memory keep growing and it became normal after replacing jemalloc.

By the way, switching to jemalloc in preload way (https://github.com/apache/incubator-gluten/issues/7397#issuecomment-2408452437) also works well, so I am not sure whether this change is necessary.

### CODE REVIEW

**Comment by FelixYBW** [comment]
we should use LD_PRELOAD, in this way all memory allocation including the one not tracked by memory pool can be allocated by jemalloc as well.

**Comment by wForget** [comment]
> we should use LD_PRELOAD, in this way all memory allocation including the one not tracked by memory pool can be allocated by jemalloc as well.

Got it, thank you. As described in https://github.com/apache/incubator-gluten/issues/6571#issue-2426589391, we have hybrid cluster with different CPU architectures, so we prefer to package the native libs of multiple environments into one package and select the appropriate lib directory at runtime.

**Comment by FelixYBW** [comment]
> Got it, thank you. As described in [#6571 (comment)](https://github.com/apache/incubator-gluten/issues/6571#issue-2426589391), we have hybrid cluster with different CPU architectures, so we prefer to package the native libs of multiple environments into one package and select the appropriate lib directory at runtime.

It's better to package the libjemalloc.so into jar, then set LD_PRELOAD path to relative address. It can also solve the potential conflicts between the one linked into Gluten and system. @PHILO-HE is it possible?

**Comment by FelixYBW** [comment]
FYI, some more info about jemalloc:
Jemalloc:

- 5.0 changed a lot. Most document online is for 4.0 and before
- Free process: dirty (physical mapped) -> muzzy(MADV_FREE) -> clean (MADV_DONTNEED)
- doesn't release virtual memory, just free physical memory
- dirty_decay_ms and muzzy_decay_ms control when to release page to OS. Default is 10s. 0 means no delay, -1 means never release
- Default 10s is good enough, may increase to 30s
- Default background thread is not useful
- Tcache size is 32k bydefault, no help when increase to 8M
- Madvise(willneed) looks useless to jemalloc allocated memory
- Huge allocation memory isn't hold by jemalloc, it will be released (retained) once free is called. oversize_threshold controls the threshold, default is 8M
- To cache all memory in pool, use param: muzzy_decay_ms:-1,dirty_decay_ms:-1,background_thread:true,oversize_threshold:5368709121
- dirty_decay_ms=10s doesn't mean the memory block wait until 10s, but keep release in the 10s and release all list by end of 10s. So to keep all page in memory pool, you need to config it as -1

image

**Comment by wForget** [comment]
@FelixYBW Thank you very much for your help.

> It's better to package the libjemalloc.so into jar, then set LD_PRELOAD path to relative address. It can also solve the potential conflicts between the one linked into Gluten and system.

Sounds good to me, I will try that.

**Comment by PHILO-HE** [comment]
> @FelixYBW Thank you very much for your help.
> 
> > It's better to package the libjemalloc.so into jar, then set LD_PRELOAD path to relative address. It can also solve the potential conflicts between the one linked into Gluten and system.
> 
> Sounds good to me, I will try that.

@wForget, @FelixYBW, maybe, one way is to pack libjemalloc.so into gluten third-party jar. And let Gluten put this lib in some fixed path (not temp path like other shared lib). Then, set env LD_PRELOAD for spark executor with that fixed lib jemalloc path.

**Comment by wForget** [comment]
Maybe we can package them into a zip file with directories like this:

```
./
└── Linux
    └── x86_64
        └── libjemalloc.so
...
```

Then specify preload jemalloc lib like this:

```
spark.yarn.dist.archives=/path/to/jemallocs.zip
spark.executorEnv.LD_PRELOAD=./jemallocs.zip/$(uname)/$(uname -m)/libjemalloc.so
```

**Comment by FelixYBW** [comment]
> 
> @wForget, @FelixYBW, maybe, one way is to pack libjemalloc.so into gluten third-party jar. And let Gluten put this lib in some fixed path (not temp path like other shared lib) on executor node. Then, configure env LD_PRELOAD for spark executor with that fixed lib jemalloc path.

For static link, we don't have a thirt-party jar.

**Pull request closed without merging**
