### PR TITLE
[DNM] Test simd hash

### PR DESCRIPTION
**Pull request by zhli1142015**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by zhouyuan** [comment]
CC @PHILO-HE

**Comment by zhli1142015** [comment]
> CC @PHILO-HE

This is just a test PR to verify my velox changes, https://github.com/facebookincubator/velox/pull/10301 and https://github.com/facebookincubator/velox/pull/10273.
You don't need to look at this, od do you see any issue related to this?

**Comment by zhouyuan** [comment]
> > CC @PHILO-HE
> 
> This is just a test PR to verify my velox changes, [facebookincubator/velox#10301](https://github.com/facebookincubator/velox/pull/10301) and [facebookincubator/velox#10273](https://github.com/facebookincubator/velox/pull/10273). You don't need to look at this, or do you see any issue related to this?

@zhli1142015 Yes we do see an optimized lib better than re2 for regex workload, @PHILO-HE is looking on this part

**Pull request closed without merging**
