### PR TITLE
[GLUTEN-5656][CORE] Avoid executing subqueries with complex data type during validation

### PR DESCRIPTION
**Pull request by zhztheplayer**
Fixes https://github.com/apache/incubator-gluten/issues/5656

### CODE REVIEW

**Comment by zhztheplayer** [comment]
There is an error may not relate to this change 

```
GlutenOrcV2SchemaPruningSuite:
- Spark vectorized reader - without partition data column - select only top-level fields !!! IGNORED !!!
- Spark vectorized reader - with partition data column - select only top-level fields !!! IGNORED !!!
- Non-vectorized reader - without partition data column - select only top-level fields
- Non-vectorized reader - with partition data column - select only top-level fields
- Spark vectorized reader - without partition data column - select a single complex field with disabled nested schema pruning !!! IGNORED !!!
- Spark vectorized reader - with partition data column - select a single complex field with disabled nested schema pruning !!! IGNORED !!!
- Non-vectorized reader - without partition data column - select a single complex field with disabled nested schema pruning !!! IGNORED !!!
- Non-vectorized reader - with partition data column - select a single complex field with disabled nested schema pruning !!! IGNORED !!!
- Spark vectorized reader - without partition data column - select only input_file_name()
- Spark vectorized reader - with partition data column - select only input_file_name()
- Non-vectorized reader - without partition data column - select only input_file_name()
- Non-vectorized reader - with partition data column - select only input_file_name()
pure virtual method called
terminate called without an active exception
```

https://github.com/apache/incubator-gluten/actions/runs/8998521030/job/24718799749?pr=5658

**Review by Yohahaha — APPROVED** [review]
great fix, thank you!

**Pull request merged**
