### PR TITLE
[Core] Supports generating nested complex type in RandomParquetDataGenerator

### PR DESCRIPTION
**Pull request by marin-ma**
Supports generating randomized schema for nested complex datatypes. Add `RowToColumnarFuzzerTest` and some code refactoring.

### CODE REVIEW

**Comment by marin-ma** [comment]
@FelixYBW @yma11 
Seems like there's a high probability to get the result mismatch error with nested complex types. e.g. run test "reproduce" with seed 1711691870863L

```
  test("reproduce") {
    // Replace sql with the actual failed sql.
    val sql = REPARTITION_SQL(1)
    // Replace seed '0L' with the actual failed seed.
    Seq(1711691870863L).foreach {
      seed =>
        dataGenerator.reFake(seed)
        logWarning(
          s"==============================> " +
            s"Started reproduction (seed: ${dataGenerator.getSeed})")
        val result = executeQuery(sql)
        assert(result.isInstanceOf[Successful], s"Failed to run 'reproduce' with seed: $seed")
    }
  }
```

**Comment by FelixYBW** [comment]
Thank you, Yes. It's expected now. There are several fixes going to upstream to velox. Let's add this firstly.

**Comment by marin-ma** [comment]
@PHILO-HE As there are physical operators like `ColumnarShuffleExchange` `RowToVeloxColumnarExec` which are not "fallback" operators, this patch renames below test methods:
rename `checkOperatorMatch` -> `checkTransformerMatch`
rename `checkFallbackOperatorMatch` -> `checkOperatorMatch`

**Comment by PHILO-HE** [comment]
> @PHILO-HE As there are physical operators like `ColumnarShuffleExchange` `RowToVeloxColumnarExec` which are not "fallback" operators, this patch renames below test methods: rename `checkOperatorMatch` -> `checkTransformerMatch` rename `checkFallbackOperatorMatch` -> `checkOperatorMatch`

@marin-ma, maybe, better to rename the original `checkOperatorMatch` to `checkGlutenOperatorMatch` (see below code, where `TransformerSupport` has been replaced by `GlutenPlan`), and the other to `checkSparkOperatorMatch`?

```
  def checkGlutenOperatorMatch[T <: GlutenPlan](df: DataFrame)(implicit tag: ClassTag[T]): Unit = {
```
Then,  gluten's shuffle, C2R, R2C operator can be checked with `checkGlutenOperatorMatch`.

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Comment by marin-ma** [comment]
> @FelixYBW @yma11 Seems like there's a high probability to get the result mismatch error with nested complex types. e.g. run test "reproduce" with seed 1711691870863L
> 
> ```
>   test("reproduce") {
>     // Replace sql with the actual failed sql.
>     val sql = REPARTITION_SQL(1)
>     // Replace seed '0L' with the actual failed seed.
>     Seq(1711691870863L).foreach {
>       seed =>
>         dataGenerator.reFake(seed)
>         logWarning(
>           s"==============================> " +
>             s"Started reproduction (seed: ${dataGenerator.getSeed})")
>         val result = executeQuery(sql)
>         assert(result.isInstanceOf[Successful], s"Failed to run 'reproduce' with seed: $seed")
>     }
>   }
> ```

Note the test failure was due to the result was misjudged from the framework itself. Two `Array[Byte]` (BinaryType) in nested complex types with same elements will be marked as non-equal result, but a simple BinaryType will be converted to `Seq[Byte]` so it can pass the test. Simply removed the `BinaryType` from the leaf child of nested complex type.

**Comment by FelixYBW** [comment]
Are the fuzzer tests in CI or Jenkins? Or just run once?
@zhouyuan

**Comment by marin-ma** [comment]
> Are the fuzzer tests in CI or Jenkins? Or just run once? @zhouyuan

They are not enabled in CI

**Pull request merged**
