### PR TITLE
[GLUTEN-7023][CH] Shade dependency jars

### PR DESCRIPTION
**Pull request by loudongfeng**
## What changes were proposed in this pull request?

Shade clickhouse backend dependency jars

Fixes: \#7023

## How was this patch tested?

Manual verification by running basic queries.

### CODE REVIEW

**Review by zzcclp — APPROVED** [review]
LGTM

**Comment by baibaichen** [comment]
@loudongfeng hold on let's review it

**Comment by lwz9103** [comment]
It seems that some Google libraries have been shaded into the Gluten jar. Does this mean we no longer need to copy the google protobuf jar to Spark? If so, please help modify the ep/build-clickhouse/src/package.sh to remove downloading protobuf jar.

image

**Comment by loudongfeng** [comment]
> It seems that some Google libraries have been shaded into the Gluten jar. Does this mean we no longer need to copy the google protobuf jar to Spark? If so, please help modify the ep/build-clickhouse/src/package.sh to remove downloading protobuf jar.

Fixed. Also updated the document file.

**Review by baibaichen — APPROVED** [review]
LGTM

**Pull request merged**
