### PR TITLE
[VL] Add Support for tencentos 2.4

### PR DESCRIPTION
**Pull request by zhixingheyi-tian**
## What changes were proposed in this pull request?

Just add compiling support for tencentos 2.4 which is  used in Tencent cloud.

## How was this patch tested?

Manually tested in Tencent EMR env.

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by zhixingheyi-tian** [comment]
@zhouyuan @weiting-chen 
Thanks.

**Comment by weiting-chen** [comment]
@zhixingheyi-tian Since the source code has been moved to Apache domain, some source code must be refresh to new files.

**Comment by zhixingheyi-tian** [comment]
> @zhixingheyi-tian Since the source code has been moved to Apache domain, some source code must be refresh to new files.

Have rebased the newest code.

**Review by weiting-chen — APPROVED** [review]
Looks good to me.

**Pull request merged**
