### PR TITLE
[GLUTEN-6887][VL] Daily Update Velox Version (2024_10_09)

### PR DESCRIPTION
**Pull request by GlutenPerfBot**
Upstream Velox's New Commits:

```txt
acd57170b by Satadru Pan, De-flake DriverTest.pause (11202)
6a7c844d9 by Xiaoxuan Meng, Improve spill related logging (11200)
530b446f8 by Xiaoxuan Meng, Avoid additional memory allocation during sort output spill (11199)
63c848d6b by Christian Zentgraf, Fix arrow install with custom INSTALL_PREFIX (11052)
683e35940 by Jacob Wujciak-Jens, Add CODEOWNERS file (11081)
3ce3fb1cf by Ke Wang, Fix fb_reshape_row for ArrayType equal comparison
3fabdf5cf by Christian Zentgraf, Update FBOS to v2024.07.01 (11104)
f8e076eca by Reetika Agrawal, Option to enable column index based mapping for Parquet (10517)
22d73a057 by Jialiang Tan, Fix Presto serde bug when deserializing large payload (11177)
2a42006fd by duanmeng, Add HiveConnectorSplit Serde (11184)
a62a3aa21 by Deepak Majeti, Fix typo of PYTHON_VENV variable (11185)
be2baba40 by Jialiang Tan, Fix flaky test HiveConnectorSerDeTest (11194)
640592d8c by Xiaoxuan Meng, Fix data race in cache eviction path (11193)
74c2133de by duanmeng, Add HashAggregation Replayer (11176)
b63622d52 by Christian Zentgraf, Replace nproc in macOS setup script (11186)
e2231c571 by Xiaoxuan Meng, Free hash table after grouping set/row number spill to release memory plus a hash table fix (11180)
88888e758 by Daniel Hunte, Throw when null row is passed to multimap_from_entries (11166)
e014dabd9 by Daniel Hunte, Modify map_top_n to throw when nested nulls are present (11157)
514740abd by Kevin Wilfong, Add support for custom comparison in Presto's array_distinct (11143)
641193b24 by Kevin Wilfong, Add tests for array_sort with TimestampWithTImezone (11142)
2d118aabe by Kevin Wilfong, Add tests for array_min/array_max with TimestampWithTimezone (11141)
ce035c87d by Pramod, Add kRange preceding/following frames in window fuzzer (10006)
291957f9b by Kevin Wilfong, Add comment explaining TypeToFlatVector<Generic> (11187)
```

### CODE REVIEW

**Comment by FelixYBW** [comment]
> @zhztheplayer it seems the OOM test is broken

does it happen every test now?

**Comment by zhouyuan** [comment]
> > @zhztheplayer it seems the OOM test is broken
> 
> does it happen every test now

I suspect this is due to


> ```
> e2231c571 by Xiaoxuan Meng, Free hash table after grouping set/row number spill to release memory plus a hash table fix (11180)
> ```

**Review by zhouyuan — APPROVED** [review]

**Comment by FelixYBW** [comment]
> > e2231c571 by Xiaoxuan Meng, Free hash table after grouping set/row number spill to release memory plus a hash table fix (11180)
> > ```

We need to fix the OOM or revert the PR in oap/velox. It may be a common issue on customer side.

**Comment by zhouyuan** [comment]
> > > e2231c571 by Xiaoxuan Meng, Free hash table after grouping set/row number spill to release memory plus a hash table fix (11180)
> 
> We need to fix the OOM or revert the PR in oap/velox. It may be a common issue on customer side.

Agree, trying to do biset to check here

**Pull request merged**
