### PR TITLE
[GLUTEN-5434] Add script for parquet read fuzzer test

### PR DESCRIPTION
**Pull request by yma11**
## What changes were proposed in this pull request?

Leverage different version of parquet-mr to generate parquet files with random data and then verify the data using Gluten UT

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by zhouyuan** [comment]
CC @marin-ma

**Comment by marin-ma** [comment]
Thanks! Not sure if this fuzzer test can cover many cases. Looks like the data generator only generates some simple data types https://github.com/apache/parquet-mr/blob/master/parquet-benchmarks/src/main/java/org/apache/parquet/benchmarks/DataGenerator.java#L156-L165
But issues like #9242 can be related to complex data types.

**Comment by yma11** [comment]
> Thanks! Not sure if this fuzzer test can cover many cases. Looks like the data generator only generates some simple data types https://github.com/apache/parquet-mr/blob/master/parquet-benchmarks/src/main/java/org/apache/parquet/benchmarks/DataGenerator.java#L156-L165 But issues like [facebookincubator/velox#9242](https://github.com/facebookincubator/velox/issues/9242) can be related to complex data types.

Yes. The parquet-mr DataGenerator only cover simple data types as it's used for benchmark test. Complex type support is a gap. Parquet read related issues are mainly about 1) legacy format/schema that velox haven't fully covered  and 2) complex type reading if the schema can be recognized correctly, especially null/empty values. For 1), we can use script in this PR as it will generate files with different schemas as different parquet version used. We may can add more options to control generating more kinds of schemas. For 2), we can add complex type generation in it and try upstream or we can leverage the data generation in Gluten to cover null/empty values. Both are fine. What do you think?

**Comment by marin-ma** [comment]
> For 1), we can use script in this PR as it will generate files with different schemas by different parquet version used. 

Thanks for your explanation! Just one more question. Looks like the DataGenerator always generates fixed schema with random data. After adding complex types in the `DataGenerator`, will it still generate a fixed schema or we plan to support generating random schemas?

**Comment by yma11** [comment]
@zhouyuan @FelixYBW @marin-ma Scripts for building parquet read fuzzer job are all here. Please help take a review. I will need monitor the job for some days and collect initial issues. We will refine the data generator to increase more coverage. Currently it by default use parquet v2 protocol so the main problem is an issue about new v2 encoding support.

**Comment by FelixYBW** [comment]
Let's run this on our internal server only

**Pull request closed without merging**
