### PR TITLE
[GLUTEN-7311][CH] Support grace aggregate algorithm in partial aggregating stages

### PR DESCRIPTION
**Pull request by lgbo-ustc**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

Fixes: #7311 

For aggregations involve `distinct`, use grace aggregate algorithm in partial aggregating stages, instead of streaming aggregating algorithm.

Following changes are made
1. introduce `GraceAggregatingStep`. It bases on codes of `GraceMergingAggregatedStep`, and supports to generate intermediate result.
2. Make `Aggregator` to support multiple aggregate phases, change is in https://github.com/Kyligence/ClickHouse/pull/504
3. Override `AggregateFunctionPartialMerge::getBaseAggregateFunctionWithSameStateRepresentation`, resolve the failure of checking columns structure equality in aggregate phase `INTERMEDIATE_TO_INTERMEDIATE`
4. Keep `requiredChildDistributionExpressions` in `MergeTwoPhasesHashBaseAggregate` that we can determine whether a aggregate step is in completed mode.

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

 unit tests,  manual tests

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by zzcclp** [comment]
Is there any performance improved with this pr ?

**Comment by lgbo-ustc** [comment]
Run Gluten Clickhouse CI

**Review by baibaichen — APPROVED** [review]
LGTM

**Comment by lgbo-ustc** [comment]
> Is there any performance improved with this pr ?

It's not for performance

**Pull request merged**
