### PR TITLE
[GLUTEN-6279][CH] Inroduce JNI safe array

### PR DESCRIPTION
**Pull request by baibaichen**
## What changes were proposed in this pull request?

To fix memory leak, I Inroduce JNI safe array to avoid call  `ReleaseByteArrayElements` manually

(Fixes: \#6279)

## How was this patch tested?

Using existed UTs

### CODE REVIEW

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI

**Comment by exmy** [comment]
LGTM

**Review by exmy — APPROVED** [review]

**Pull request merged**
