### PR TITLE
[GLUTEN-6272] Revert #6130 

### PR DESCRIPTION
**Pull request by baibaichen**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#6272)

## How was this patch tested?

Using existed UT.

### CODE REVIEW

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI

**Comment by baibaichen** [comment]
By Reverting https://github.com/apache/incubator-gluten/pull/6130, it looks more stable than before. However, I cannot be certain of the specific reason

**Review by zzcclp — APPROVED** [review]

**Pull request merged**
