### PR TITLE
[CORE] Move CountDistinctWithoutExpand,RewriteDateTimestampComparisonRule to ch backend

### PR DESCRIPTION
**Pull request by ulysses-you**
## What changes were proposed in this pull request?

Avoid compile unnecessary class.

## How was this patch tested?

PASS CI

### CODE REVIEW

**Comment by lgbo-ustc** [comment]
Why

**Comment by ulysses-you** [comment]
> Why. These are enable in `CH`, but doesn't mean they only could be used in `CH`

Thank you @lgbo-ustc for review. This pr only mvoes rule which is dedicated for ch backend...  If a rule can be reused for other backends, it should check `BackendsApiManager.getSettings.supportxxx`, e.g., `MergeTwoPhasesHashBaseAggregate` which is also only used for ch backend but live in core.

**Comment by lgbo-ustc** [comment]
> > Why. These are enable in `CH`, but doesn't mean they only could be used in `CH`
> 
> Thank you @lgbo-ustc for review. This pr only mvoes rule which is dedicated for ch backend... If a rule can be reused for other backends, it should check `BackendsApiManager.getSettings.supportxxx`, e.g., `MergeTwoPhasesHashBaseAggregate` which is also only used for ch backend but live in core.

I think there have been settings to enable/disable there rules,

**Comment by lgbo-ustc** [comment]
It may be a problem to add rules for some common issues that could exists in backends

**Comment by ulysses-you** [comment]
I think it's not a good story to say a rule is created for one backend but say it is not designed for that backend... and at least the tests should be added into gluten-ut module for all backends and skip backend which is not enabled by default.

Do you mean `RewriteDateTimestampComparisonRule` and `CommonSubexpressionEliminateRule` are generic for velox backend ? If so ,i can leave them to core for now and see if we can help to make it work.

BTW, the `RewriteToDateExpresstionRule` and `CountDistinctWithoutExpand` are bound to ch backend code and we can move them.

**Pull request closed without merging**
