### PR TITLE
[INFRA][MINOR] Change the issueRegexp to `(?:#|GLUTEN-)(\d+)` from the vcs.xml.

### PR DESCRIPTION
**Pull request by yikf**
## What changes were proposed in this pull request?
This PR aims to change the issueRegexp to `(?:#|GLUTEN-)(\d+)` from the vcs.xml. It seems that the `GLUTEN-(\d+)` is not working if the issueRegexp is `#(\d+)|GLUTEN-(\d+)`[1].

[1] https://www.jetbrains.com/help/idea/handling-issues.html#example

## How was this patch tested?
manual tests.

### CODE REVIEW

**Comment by yikf** [comment]
@zhztheplayer @merrily01 Could you please take a look if you find a time, thanks!

**Comment by zhztheplayer** [comment]
@yikf Thanks for working on this.

Can we try change to `(?:#|GLUTEN-)(\d+)`? It's working locally from my side.

**Comment by yikf** [comment]
> @yikf Thanks for working on this.
> 
> Can we try changing to `(?:#|GLUTEN-)(\d+)`? It's working locally from my side.

@zhztheplayer It work fine, thanks.

**Review by zhztheplayer — APPROVED** [review]
Thanks!

**Comment by yikf** [comment]
> Would you update PR title as well? Thanks.

Sure, updated.

**Pull request merged**
