### PR TITLE
[CH]Daily Update Clickhouse Version (20241118)

### PR DESCRIPTION
**Pull request by liuneng1994**
## What changes were proposed in this pull request?

Manual rebase Clickhouse repo

## How was this patch tested?

unit tests

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by liuneng1994** [comment]
Run Gluten Clickhouse CI on x86

**Comment by liuneng1994** [comment]
Run Gluten Clickhouse CI on x86

**Comment by liuneng1994** [comment]
Run Gluten Clickhouse CI on x86

**Review by zzcclp — APPROVED** [review]

**Comment by liuneng1994** [comment]
wait https://github.com/apache/incubator-gluten/pull/7923

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI on x86

**Pull request merged**
