### PR TITLE
[GLUTEN-5341]Fix test write parquet with compression codec

### PR DESCRIPTION
**Pull request by ayushi-agarwal**
## What changes were proposed in this pull request?

LZ4_RAW is currently not supported in velox, so fallback to non-native write when user specifies this compression codec.
It got introduced in spark 3.5 https://issues.apache.org/jira/browse/SPARK-43273

(Partially Fixes: \#5341)

## How was this patch tested?

Ran UTs

### CODE REVIEW

**Comment by ayushi-agarwal** [comment]
@JkSelf Could you please review this PR

**Comment by ayushi-agarwal** [comment]
The tests won't pass till issue https://github.com/apache/incubator-gluten/issues/5427 gets fixed.

**Review by Yohahaha — APPROVED** [review]
thanks!

**Review by JkSelf — APPROVED** [review]
Good catch. Thanks.

**Comment by ayushi-agarwal** [comment]
@JkSelf @Yohahaha Thanks for reviewing. Could you please merge it if everything looks good.

**Pull request merged**
