### PR TITLE
[GLUTEN-5024][VL] Enhance buildbundle-veloxbe.sh to run single step

### PR DESCRIPTION
**Pull request by xumingming**
buildbundle-veloxbe.sh is composed of at least two steps:

- Get and build Velox
- Build Gluten CPP code

Currently it is not smooth to run on some platforms such as MacOS, we might need to run this script multiple times to fix a build issue, e.g. `Get and build Velox` succeed, but `Build Gluten CPP code` failed, in this PR we introduced the ability to specify the commands to run rather than run the whole script every time. By default we still run all the steps. Usage samples are the following:

```bash
-- Run all the steps
./dev/buildbundle-veloxbe.sh --build_type=RelWithDebInfo
-- Only run build_gluten_cpp
./dev/buildbundle-veloxbe.sh --build_type=RelWithDebInfo build_gluten_cpp
```

Fixes: #5024

### CODE REVIEW

**Comment by FelixYBW** [comment]
Thank you. It's something we just planed. Since build_velox is always needed, can you add one flag like -Dfetch_velox=ON/OFF which can fetch velox or not before build? by default let's set it ON. We may also check if velox is fetched if not it always fetch.

Another issue is that currently script skip the velox build even if we modified some file in velox because it check the commit id to continue. So we need a git commit --amend in velox dir to force to build. Is there any better way to build velox automatically?

**Comment by FelixYBW** [comment]
@zhztheplayer

**Comment by zhztheplayer** [comment]
Thanks @xumingming for the enhancement.

> can you add one flag like -Dfetch_velox=ON/OFF which can fetch velox or not before build? by default let's set it ON.

Yes that would be one of the commen case. I assume there could probably be a `fetch_velox` before

>   build_velox
  build_gluten_cpp 

Though I am not sure if it's trivial to add. If this tricky we can apply this PR and do the further step by step.

**Comment by FelixYBW** [comment]
>Another issue is that currently script skip the velox build even if we modified some file in velox because it check the commit id to continue. So we need a git commit --amend in velox dir to force to build. Is there any better way to build velox automatically?

Let's fix this issue at least. It's really not good experience to run git commit --amend each time

**Review by FelixYBW — APPROVED** [review]

**Pull request merged**
