### PR TITLE
[VL] Support row type and fix subfield in filter push-down

### PR DESCRIPTION
**Pull request by rui-mo**
## What changes were proposed in this pull request?

Supports the push-down of IsNull and IsNotNull filter for row type.
Filter on subfield cannot be pushed-down, and we put them in the remaining filter.

## How was this patch tested?

With unit test.

### CODE REVIEW

**Review by rui-mo — COMMENTED** [review]
@FelixYBW @PHILO-HE Could you help take a review? Thanks.

**Review by PHILO-HE — APPROVED** [review]
Looks nice! cc @FelixYBW

**Comment by zhli1142015** [comment]
One question here about the lgoic here.
I thought there is already logic to split filters to subfield filters and remaining filters in Velox: https://github.com/facebookincubator/velox/blob/main/velox/connectors/hive/HiveConnectorUtil.cpp#L790
I wonder what's the reason we maintain similar logic here. Thanks.

**Comment by rui-mo** [comment]
> One question about the lgoic here. I thought there is already logic to split filters to subfield filters and remaining filters in Velox: https://github.com/facebookincubator/velox/blob/main/velox/connectors/hive/HiveConnectorUtil.cpp#L790 I wonder what's the reason we maintain similar logic here or what's the difference between them. Thanks.

@zhli1142015 Thanks for bringing this up. We were using our implementation from the start since Velox added the function `extractFiltersFromRemainingFilter` after we implemented it in Gluten. One distinction I see is that Gluten eliminates the filters to be pushed down from the call expression, whereas Velox does not. Before taking use of the Velox implementation, we might need to verify Gluten supported cases and fix the met issue if there is. We can then seamlessly transition to the Velox implementation. @FelixYBW Do you have any suggestion? Thanks.

**Comment by FelixYBW** [comment]
> 
> @zhli1142015 Thanks for bringing this up. We were using our implementation from the start since Velox added the function `extractFiltersFromRemainingFilter` after we implemented it in Gluten. One distinction I see is that Gluten eliminates the filters to be pushed down from the call expression, whereas Velox does not. Before taking use of the Velox implementation, we might need to verify Gluten supported cases and fix the met issue if there is. We can then seamlessly transition to the Velox implementation. @FelixYBW Do you have any suggestion? Thanks.

Compared to Velox's, Is there any logic we missed?

**Review by FelixYBW — APPROVED** [review]

**Comment by FelixYBW** [comment]
Thank you, Rui for your fix.

**Comment by rui-mo** [comment]
> Compared to Velox's, Is there any logic we missed?

@FelixYBW I notice Velox supports the pushdown of `between` and `neq`, while Gluten does not. While a previous quick trial shows Velox's implementation could create subfield filters that are supported, which leads to runtime exception. We might need to do a full validation before using it.

**Comment by FelixYBW** [comment]
> @FelixYBW I notice Velox supports the pushdown of `between` and `neq`, while Gluten does not. But a previous quick trial shows Velox's implementation could create subfield filters that are not supported, which leads to runtime exception. We might need to do a full validation before using it.

Thank you, Rui. Can you create an enhancement issue to track?

**Comment by rui-mo** [comment]
@FelixYBW Opened an issue to track https://github.com/apache/incubator-gluten/issues/6666.

**Pull request merged**
