### PR TITLE
[GLUTEN-6387][CH] support percentile function

### PR DESCRIPTION
**Pull request by taiyang-li**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#6387)

``` sql 
0: jdbc:hive2://localhost:10000/> select  l_linenumber % 10,  percentile(l_extendedprice, array(0.1, 0.2, 0.3), l_orderkey) from lineitem group by   l_linenumber % 10;  
+----------------------+----------------------------------------------------+
| (l_linenumber % 10)  | percentile(l_extendedprice, array(0.1, 0.2, 0.3), l_orderkey) |
+----------------------+----------------------------------------------------+
| 7                    | [7666.26,14514.3,21056.23]                         |
| 6                    | [7526.19,14375.04,21068.44]                        |
| 5                    | [7369.92,14155.26,20930.0]                         |
| 1                    | [7413.98,14172.18,20884.32]                        |
| 3                    | [7462.85,14307.36,21036.26]                        |
| 2                    | [7517.9,14361.12,21082.5]                          |
| 4                    | [7295.68,14094.08,20866.67]                        |
+----------------------+----------------------------------------------------+
7 rows selected (2.431 seconds)
0: jdbc:hive2://localhost:10000/> set spark.gluten.enabled = false;
+-----------------------+--------+
|          key          | value  |
+-----------------------+--------+
| spark.gluten.enabled  | false  |
+-----------------------+--------+
1 row selected (0.053 seconds)
0: jdbc:hive2://localhost:10000/> select  l_linenumber % 10,  percentile(l_extendedprice, array(0.1, 0.2, 0.3), l_orderkey) from lineitem group by   l_linenumber % 10;  
+----------------------+----------------------------------------------------+
| (l_linenumber % 10)  | percentile(l_extendedprice, array(0.1, 0.2, 0.3), l_orderkey) |
+----------------------+----------------------------------------------------+
| 7                    | [7666.26,14514.3,21056.23]                         |
| 6                    | [7526.19,14375.04,21068.44]                        |
| 5                    | [7369.92,14155.26,20930.0]                         |
| 1                    | [7413.98,14172.18,20884.32]                        |
| 3                    | [7462.85,14307.36,21036.26]                        |
| 2                    | [7517.9,14361.12,21082.5]                          |
| 4                    | [7295.68,14094.08,20866.67]                        |
+----------------------+----------------------------------------------------+
7 rows selected (3.773 seconds)
```

### CODE REVIEW

**Review by PHILO-HE — DISMISSED** [review]
Just reviewed core/velox module code. Looks nice! Thanks!

**Comment by exmy** [comment]
It seems missing `PercentileSuite` in Spark ut. Could you help add this suite?

**Comment by taiyang-li** [comment]
> It seems missing `PercentileSuite` in Spark ut. Could you help add this suite?

done

**Comment by taiyang-li** [comment]
failed ut can't be reproduced using spark-sql  

"Support filter clause for aggregate function uses SortAggregateExec"
```
set  spark.sql.execution.useObjectHashAggregateExec = false;
CREATE TABLE testData2 (a INT, b INT);
INSERT INTO testData2 VALUES (1, 1), (1, 2), (2, 1), (2, 2), (3, 1), (3, 2);
SELECT PERCENTILE(a, 1) FILTER (WHERE b > 1) FROM testData2 
```

**Review by baibaichen — APPROVED** [review]

**Pull request merged**
