### PR TITLE
[GLUTEN-6951][CORE][CH] Move CustomerExpressionTransformer to CH backend

### PR DESCRIPTION
**Pull request by zhztheplayer**
CustomerExpressionTransformer was added to core module in https://github.com/apache/incubator-gluten/pull/1937 however is not used by Velox backend for long time. Propose to move its code and planner rules to CH backend.

Changes:

1. Drop support of config option `a.g.s.c.extended.expressions.transformer` from Velox backend
2. Move code related to `CustomerExpressionTransformer ` from core to CH backend
3. Essential code refactors

### CODE REVIEW

**Comment by zhztheplayer** [comment]
@liujiayi771 @Yohahaha @ulysses-you @kecookier @zhli1142015 (and all Velox backend users/developers)

Please let me know if you rely on the feature. Otherwise we'll remove then.

**Comment by zhztheplayer** [comment]
@zzcclp What do you think about this? Thanks.

**Comment by Yohahaha** [comment]
We are not rely on this functionality for now.

**Comment by ulysses-you** [comment]
+1

**Comment by baibaichen** [comment]
let me move test to backends clickhouse first.

**Comment by liujiayi771** [comment]
+1

**Comment by zzcclp** [comment]
please move `spark32/src/test/scala/org/apache/spark/sql/extension/CustomerExpressionTransformer.scala`, `spark32/src/test/scala/org/apache/spark/sql/extension/GlutenCustomerExpressionTransformerSuite.scala` to CH backend module too.

**Comment by zhztheplayer** [comment]
> please move `spark32/src/test/scala/org/apache/spark/sql/extension/CustomerExpressionTransformer.scala`, `spark32/src/test/scala/org/apache/spark/sql/extension/GlutenCustomerExpressionTransformerSuite.scala` to CH backend module too.

I am moving it. It caused Velox's test failure.

**Review by zzcclp — APPROVED** [review]
LGTM

**Comment by zhztheplayer** [comment]
@zzcclp Thanks!

**Pull request merged**
