### PR TITLE
[GLUTEN-7283][CORE] Support DynamicPruningExpression conversion

### PR DESCRIPTION
**Pull request by wForget**
## What changes were proposed in this pull request?

Support DynamicPruningExpression conversion

Fixes: #7283

## How was this patch tested?

added unit test

### CODE REVIEW

**Comment by wForget** [comment]
@zhztheplayer @PHILO-HE Could you please take a look?

**Review by PHILO-HE — DISMISSED** [review]
Looks good! cc @zzcclp

**Review by zhztheplayer — APPROVED** [review]
What's the real use case of `ChildTransformer`? Can we just remove it?

cc @zzcclp

**Comment by wForget** [comment]
> What's the real use case of `ChildTransformer`? Can we just remove it?

I have the same confusion, it seems to be just a placeholder. If it's no longer needed I'll open a new PR to remove it.

**Review by zzcclp — APPROVED** [review]
LGTM

**Pull request merged**
