### PR TITLE
[GLUTEN-6887][VL] Daily Update Velox Version (2024_08_20)

### PR DESCRIPTION
**Pull request by GlutenPerfBot**
Upstream Velox's New Commits:

```txt
be529880b by Orri Erling, Wave Metrics (10679)
676b17019 by Hongze Zhang, Add gflag to allow growing buffers that were created in different task (10768)
```

### CODE REVIEW

**Comment by zhouyuan** [comment]
CC @zhztheplayer shall we fix the memory issue since your fix is landed in Velox?

**Comment by zhouyuan** [comment]
@GlutenPerfBot benchmark

**Comment by zhztheplayer** [comment]
Error

```
Executing SQL query from resource path /tpcds-queries/q24b.sql...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fd86d9bd966, pid=6067, tid=0x00007fd874626700
#
# JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)
# Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libvelox.so+0x1807966]  facebook::velox::memory::ScopedMemoryPoolArbitrationCtx::~ScopedMemoryPoolArbitrationCtx()+0x6
#
# Core dump written. Default location: /__w/incubator-gluten/incubator-gluten/tools/gluten-it/core or core.6067
#
# An error report file with more information is saved as:
# /__w/incubator-gluten/incubator-gluten/tools/gluten-it/hs_err_pid6067.log
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%208&component=java-1.8.0-openjdk
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
sbin/gluten-it.sh: line 50:  6067 Aborted                 (core dumped) $JAVA_HOME/bin/java $SPARK_JVM_OPTIONS $GLUTEN_IT_JVM_ARGS -XX:ErrorFile=/var/log/java/hs_err_pid%p.log -Dio.netty.tryReflectionSetAccessible=true -cp $JAR_PATH org.apache.gluten.integration.Cli $@
```

**Comment by zhztheplayer** [comment]
> CC @zhztheplayer shall we fix the memory issue since your fix is landed in Velox?

Yes and I'll raise another PR today for that, we can merge this first.

**Review by zhztheplayer — APPROVED** [review]

**Comment by zhouyuan** [comment]
> Error
> 
> ```
> Executing SQL query from resource path /tpcds-queries/q24b.sql...
> #
> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  SIGSEGV (0xb) at pc=0x00007fd86d9bd966, pid=6067, tid=0x00007fd874626700
> #
> # JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)
> # Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode linux-amd64 compressed oops)
> # Problematic frame:
> # C  [libvelox.so+0x1807966]  facebook::velox::memory::ScopedMemoryPoolArbitrationCtx::~ScopedMemoryPoolArbitrationCtx()+0x6
> #
> # Core dump written. Default location: /__w/incubator-gluten/incubator-gluten/tools/gluten-it/core or core.6067
> #
> # An error report file with more information is saved as:
> # /__w/incubator-gluten/incubator-gluten/tools/gluten-it/hs_err_pid6067.log
> #
> # If you would like to submit a bug report, please visit:
> #   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%208&component=java-1.8.0-openjdk
> # The crash happened outside the Java Virtual Machine in native code.
> # See problematic frame for where to report the bug.
> #
> sbin/gluten-it.sh: line 50:  6067 Aborted                 (core dumped) $JAVA_HOME/bin/java $SPARK_JVM_OPTIONS $GLUTEN_IT_JVM_ARGS -XX:ErrorFile=/var/log/java/hs_err_pid%p.log -Dio.netty.tryReflectionSetAccessible=true -cp $JAR_PATH org.apache.gluten.integration.Cli $@
> ```

re-trigger it seems passing now, fired one issue to track
https://github.com/apache/incubator-gluten/issues/6930

**Pull request merged**
