### PR TITLE
[GLUTEN-4896] Upgrade Spark33 version to Spark3.3.4

### LINKED ISSUE #4896: Bump Spark33 version to Spark3.3.3
### Description

As title

### PR DESCRIPTION
**Pull request by zwangsheng**
## What changes were proposed in this pull request?

Close #4896

## How was this patch tested?

Exist UT

### CODE REVIEW

**Comment by zhouyuan** [comment]
I think this may need to upgrade the docker image which contains Spark 331 code
https://github.com/apache/incubator-gluten/blob/main/.github/workflows/velox_be.yml#L177

**Comment by zwangsheng** [comment]
> I think this may need to upgrade the docker image which contains Spark 331 code https://github.com/apache/incubator-gluten/blob/main/.github/workflows/velox_be.yml#L177

Thanks for you info, i will go on with this.

**Comment by zwangsheng** [comment]
> I think this may need to upgrade the docker image which contains Spark 331 code https://github.com/apache/incubator-gluten/blob/main/.github/workflows/velox_be.yml#L177

@zhouyuan Hi, I'm still confuse how to upgrade docker image, is here any document about this?

**Comment by zhouyuan** [comment]
> > I think this may need to upgrade the docker image which contains Spark 331 code https://github.com/apache/incubator-gluten/blob/main/.github/workflows/velox_be.yml#L177
> 
> @zhouyuan Hi, I'm still confuse how to upgrade docker image, is here any document about this?

Hi @zwangsheng ,

The dockerfile is hosted here:
https://github.com/apache/incubator-gluten/blob/main/tools/gluten-te/ubuntu/dockerfile-buildenv#L111
on our nightly Jenkins it will try to build the new image, and push to local docker registry.


I'm trying to remove spark compile when run gluten UTs, in this way the spark source code can be removed. 
Would you mind wait for this patch if it's not urgent request?
https://github.com/apache/incubator-gluten/pull/4955

Btw, for now all the tests are running on servers inside intel lab, we are migrating to Apache servers gradually. https://github.com/apache/incubator-gluten/issues/4917

Thanks, 
-yuan

**Pull request closed without merging**
