### PR TITLE
DNM

### PR DESCRIPTION
**Pull request by acvictor**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by FelixYBW** [comment]
Can you comment a bit how these info are used by Velox? Is it aligned with Spark's behavior?

**Comment by gaoyangxiaozhu** [comment]
can't we leverage `metadatacolumns` for this since it already contains `fileSize` and `modifyTime` ?

**Comment by acvictor** [comment]
> can't we leverage `metadatacolumns` for this since it already contains `fileSize` and `modifyTime` ?

Does `metadatacolumns` always contain file size and modification time? I understood it as containing these only if they are being queried. In this case I want it to always be passed in the split.

**Comment by acvictor** [comment]
> Can you comment a bit how these info are used by Velox? Is it aligned with Spark's behavior?

In Spark, properties are present in the split and obtained during listing. Earlier Velox would make one additional call to remote storage to fetch file length per openFileForRead call on a path even though this information is already present upstream wihle constructing the split. Velox now allows these values to be passed from the caller. By making this change we can eliminate one additional call to remote storage per path (RTT is in the order of 10s of milli seconds).

**Pull request closed without merging**
