### PR TITLE
[VL] Daily Update Velox Version (2024_03_15)

### PR DESCRIPTION
**Pull request by GlutenPerfBot**
Velox Upstream New Commits:

```txt
8f9520868 by Masha Basmanova, Document usage of generic types in Simple Function API (9084)
adc016630 by Masha Basmanova, Harden GenericViewTest::toString() (9085)
704113a7a by Krishna Pai, Remove implicit fall through in Spark SumAggregates (9081)
177ff56f9 by Orri Erling, make PrestoSerializer compression compatible with Presto and add stats (8851)
c71ed7d0d by Orri Erling, Vector reencoding utilities (8875)
6dba462cc by zhli1142015, Add uuid Spark function (9056)
e5fa5e6a7 by Ankita Victor, Add from_utc_timestamp, to_utc_timestamp Spark function (8868)
b9921cb33 by xiaoxmeng, Fix hash join changes for probe side spilling support (8996)
3c4747688 by wypb, Fix documentation for TIMESTAMP_WITH_TIME_ZONE type (9042)
399345de4 by Masha Basmanova, Add map_subset Presto function (9075)
587faab7d by Masha Basmanova, Remove deprecated VELOX_UDF_BEGIN macro from benchmarks (9080)
83397d84f by 8dukongjian, Add more linear regression Presto aggregate functions (8381)
00168e574 by Ma, Rong, Avoid overflow in IntervalYearMonthType::valueToString (9061)
8aef29c25 by Masha Basmanova, Add GenericView::toString() API for debugging (9077)
b9651c829 by Masha Basmanova, Add map_top_n Presto function (9074)
6c25f11bf by Masha Basmanova, Add DecodedVector::toString(idx) API for debugging (9076)
312551226 by xiaoxmeng, Extend join fuzzer to cover group execution mode (9045)
33fe33a47 by Pedro Pedreira, Disable CI jobs that relied on torcharrow scripts (9013)
```

### CODE REVIEW

**Comment by PHILO-HE** [comment]
@yma11, we have updated centos-8 docker image for fixing the CI failure.

Please change the version for all boost libs from 1.72.0 to 1.84.0 in this Gluten script. Thanks!
https://github.com/apache/incubator-gluten/blob/main/dev/package.sh

**Comment by zhouyuan** [comment]
@PHILO-HE Jiayi made a patch here:
https://github.com/apache/incubator-gluten/pull/4974

**Comment by PHILO-HE** [comment]
> @PHILO-HE Jiayi made a patch here: #4974

Let's merge #4974 firstly. After that, let's rebase this PR.

FYI, this rebase includes some velox code requires higher version for boost (minimum 1.77.0).

**Review by zhouyuan — APPROVED** [review]
Centos8 tests passed

**Pull request merged**
