### PR TITLE
[VL] Set Arrow_SOURCE to AUTO to allow using system arrow libs

### PR DESCRIPTION
**Pull request by PHILO-HE**
## What changes were proposed in this pull request?

Depends on the fix in https://github.com/facebookincubator/velox/pull/10355.

## How was this patch tested?

CI.

### CODE REVIEW

**Comment by Yohahaha** [comment]
```
      set_target_properties(
        Arrow::${LIB_NAME}
        PROPERTIES IMPORTED_LOCATION ${ARROW_LIB_${LIB_NAME}}
                   INTERFACE_INCLUDE_DIRECTORIES ${ARROW_HOME}/install/include)
```

if use system arrow, seems gluten still use `${ARROW_HOME}/install/include` as include dir.

**Comment by PHILO-HE** [comment]
> ```
>       set_target_properties(
>         Arrow::${LIB_NAME}
>         PROPERTIES IMPORTED_LOCATION ${ARROW_LIB_${LIB_NAME}}
>                    INTERFACE_INCLUDE_DIRECTORIES ${ARROW_HOME}/install/include)
> ```
> 
> if use system arrow, seems gluten still use `${ARROW_HOME}/install/include` as include dir.

@Yohahaha, thanks for your comment! I just removed the setting for arrow include directories, as they are actually not needed in Gluten.

**Comment by Yohahaha** [comment]
```
set(ARROW_INCLUDE_DIR "${ARROW_INSTALL_DIR}/include")
```

this line should also be removed.

**Comment by PHILO-HE** [comment]
> ```
> set(ARROW_INCLUDE_DIR "${ARROW_INSTALL_DIR}/include")
> ```
> 
> this line should also be removed.

@Yohahaha, yes, just removed. Thanks!

**Comment by PHILO-HE** [comment]
@Yohahaha, the corresponding velox patch has been merged. Do you have any other comment on this gluten PR?

**Comment by Yohahaha** [comment]
> @Yohahaha, the corresponding velox patch has been merged. Do you have any other comment on this gluten PR?

If arrow has installed in other places, seems we still set ARROW_HOME under velox path, could you clarify?

```
if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
  set(ARROW_HOME
      ${VELOX_HOME}/_build/debug/CMake/resolve_dependency_modules/arrow/arrow_ep/
  )
else()
  set(ARROW_HOME
      ${VELOX_HOME}/_build/release/CMake/resolve_dependency_modules/arrow/arrow_ep
  )
endif()
```

**Comment by Yohahaha** [comment]
> > @Yohahaha, the corresponding velox patch has been merged. Do you have any other comment on this gluten PR?
> 
> If arrow has installed in other places, seems we still set ARROW_HOME under velox path, could you clarify?
> 
> ```
> if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
>   set(ARROW_HOME
>       ${VELOX_HOME}/_build/debug/CMake/resolve_dependency_modules/arrow/arrow_ep/
>   )
> else()
>   set(ARROW_HOME
>       ${VELOX_HOME}/_build/release/CMake/resolve_dependency_modules/arrow/arrow_ep
>   )
> endif()
> ```

mayby it's not an issue, `find_library` should find correct arrow lib if ARROW_HOME is wrong.

**Comment by PHILO-HE** [comment]
@Yohahaha, thanks for your comment! The arrow home is set to let cmake firstly find arrow libs from that path. If it does not exist (because velox finds the lib from system, then it doesn't build arrow from source), cmake will find the libs from system. Though we always expect cmake in Gluten/Velox finds the libs from system now, it may be good to still keep the arrow home path for debugging (e.g., by `export Arrow_SOURCE=BUNDELD`, we can mandatorily use bundled arrow to exclude any issues due to system arrow).

**Review by zhouyuan — APPROVED** [review]

**Pull request merged**
