### PR TITLE
[VL] Support columnar collect limit

### PR DESCRIPTION
**Pull request by ulysses-you**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by yma11** [comment]
@ulysses-you I noticed that there is an existing [PR](https://github.com/apache/incubator-gluten/pull/5269) about collect limit support but may have some different coverage. You may can take a look to avoid some duplicated work. FYI.

**Comment by zhztheplayer** [comment]
> @ulysses-you I noticed that there is an existing [PR](https://github.com/apache/incubator-gluten/pull/5269) about collect limit support but may have some different coverage. You may can take a look to avoid some duplicated work. FYI.

Seems to be that this PR was opened a little bit earlier than https://github.com/apache/incubator-gluten/pull/5269. 

So @ulysses-you @guixiaowen thank both of you for taking this part of work. Do you think we should decide using which PR before continuing on this?

**Comment by guixiaowen** [comment]
> > @ulysses-you I noticed that there is an existing [PR](https://github.com/apache/incubator-gluten/pull/5269) about collect limit support but may have some different coverage. You may can take a look to avoid some duplicated work. FYI.
> 
> Seems to be that this PR was opened a little bit earlier than #5269.
> 
> So @ulysses-you @guixiaowen thank both of you for taking this part of work. Do you think we should decide using which PR before continuing on this?

@zhztheplayer  @ulysses-you  hi both, I'm very sorry for not paying attention to this review. I replied a bit late. I mentioned issues before and didn't notice that @ulysses-you  had already been submitted before me. If the evaluation criteria were based on the order of submission, @ulysses-you's  should be used.  @zhztheplayer  Thank you for your review. I will close my pr later.

**Comment by zhztheplayer** [comment]
>  If the evaluation criteria were based on the order of submission, @ulysses-you's should be used.

@guixiaowen We don't have strong criteria on this, so don't worry. Let's just decide using which one first so we can avoid duplicating work so wasting contributor's time.

**Comment by zhztheplayer** [comment]
@guixiaowen I just confirmed with @ulysses-you, let’s continue with your pr #5269. So please proceed. Thank you!

**Comment by guixiaowen** [comment]
> @guixiaowen I just confirmed with @ulysses-you, let’s continue with your pr #5269. So please proceed. Thank you!

@zhztheplayer Ok. Thank you  for your review.

**Comment by ulysses-you** [comment]
thank you @zhztheplayer and @guixiaowen, I'm on vacation so please go ahead with your pr.

**Pull request closed without merging**
