### PR TITLE
[VL] Enable from_utc_timestamp Spark function

### PR DESCRIPTION
**Pull request by acvictor**
## What changes were proposed in this pull request?

Enable from_utc_timestamp Spark function

## How was this patch tested?

Added UT and Spark tests.

### CODE REVIEW

**Comment by acvictor** [comment]
@PHILO-HE can you please review? Thank you!

**Review by PHILO-HE — APPROVED** [review]
Looks good! @acvictor, thanks!

**Comment by PHILO-HE** [comment]
Hi @acvictor, please rebase the code and resolve code conflict. Will merge the patch after that. Thanks!

**Comment by acvictor** [comment]
> Hi @acvictor, please rebase the code and resolve code conflict. Will merge the patch after that. Thanks!

Thank you @PHILO-HE! I have rebased the branch.

**Pull request merged**
