### PR TITLE
[GLUTEN-7012][SHIMS] Make spark shim provider configurable

### LINKED ISSUE #7012: [SHIMS] Make spark shim provider configurable
### Description

Our internal spark version is not consistent with the community version, which causes gluten spark shims not to be loaded correctly, so I want to make the gluten spark shim provider configurable.

### PR DESCRIPTION
**Pull request by wForget**
## What changes were proposed in this pull request?

Make spark shim provider configurable

closes #7012

## How was this patch tested?

TODO

### CODE REVIEW

**Comment by zhztheplayer** [comment]
What's the use case of this feature? I think shim layers may require refactors in near future so we may hardly maintain a stable interface.

**Comment by wForget** [comment]
> What's the use case of this feature? I think shim layers may require refactors in near future so we may hardly maintain a stable interface.

Our internal spark version is based on 3.5.0 and actually backports most of the features of the 3.5 branch. I want to make gluten spark 3.5 shim work by configuring.

**Comment by wForget** [comment]
> I think shim layers may require refactors in near future so we may hardly maintain a stable interface.

I'm not trying to implement custom SparkShims, it's just that the current SparkShims loading is too strict.

**Comment by zhztheplayer** [comment]
> > I think shim layers may require refactors in near future so we may hardly maintain a stable interface.
> 
> I'm not trying to implement custom SparkShims, it's just that the current SparkShims loading is too strict.

So in your use case, the code of 3.5.0 shim will still be replaced in Gluten? Perhaps in your Gluten fork repo?

**Comment by wForget** [comment]
> So in your use case, the code of 3.5.0 shim will still be replaced in Gluten?

Yeah, I want to make gluten spark35 shims work internal spark 3.5.0 version.

> Perhaps in your Gluten fork repo?

Thank you, I will do that if this PR doesn't get accepted.

**Comment by zhztheplayer** [comment]
> Thank you, I will do that if this PR doesn't get accepted.

My thought was, if you already have a Gluten fork, the we can put off merging this kind of PR, since the same job can be done in your forked repo.

Otherwise if you directly use upstream Gluten with 3.5.0 Spark, then perhaps we could proceed.

**Comment by wForget** [comment]
> My thought was, if you already have a Gluten fork, the we can put off merging this kind of PR, since the same job can be done in your forked repo.

Thanks, this is feasible for us, we have a gluten fork repo.

**Comment by wForget** [comment]
> SparkShimLoader: Using Shim provider: List(org.apache.gluten.sql.shims.spark35.SparkShimProvider@3a2a959e)

@zhztheplayer Sorry, I missed this log, actually `org.apache.gluten.sql.shims.spark35.SparkShimProvider` is effective for spark 3.5.0, so the current PR is unnecessary and I will close it.

**Pull request closed without merging**
