### PR TITLE
[GLUTEN-4917][VL][CI] Enable Gluten CPP tests

### PR DESCRIPTION
**Pull request by PHILO-HE**
## What changes were proposed in this pull request?

Simply a follow-up for https://github.com/apache/incubator-gluten/pull/4936.

### CODE REVIEW

**Comment by PHILO-HE** [comment]
Hi @kerwin-zk, I'm re-enabling celeborn test in the new CI. The below error is reported when stopping worker/master. Did you encounter this issue before?

```
waiting for worker graceful shutdown, wait for 599s
waiting for worker graceful shutdown, wait for 600s
Failed to stop server(pid=6960) after 600s
Error: Process completed with exit code 1.
```

**Comment by kerwin-zk** [comment]
> waiting for worker graceful shutdown, wait for 599s
> waiting for worker graceful shutdown, wait for 600s
> Failed to stop server(pid=6960) after 600s
> Error: Process completed with exit code 1.

@PHILO-HE Usually it is because there is a shuffle that has not yet ended when stopping, so it will wait for 600s.

**Comment by kerwin-zk** [comment]
> There's one line of error log, is this related? `/opt/celeborn/conf/celeborn-env.sh: line 1: -e: command not found`

@PHILO-HE @zhouyuan This exception seems to be a problem with the command written in celeborn-env.sh. It is recommended to print out the contents of celeborn-env.sh and check it.

**Comment by PHILO-HE** [comment]
> > There's one line of error log, is this related? `/opt/celeborn/conf/celeborn-env.sh: line 1: -e: command not found`
> 
> @PHILO-HE @zhouyuan This exception seems to be a problem with the command written in celeborn-env.sh. It is recommended to print out the contents of celeborn-env.sh and check it.

@kerwin-zk, thanks for your suggestion! I will check that in local docker. FYI. just created a separate pr to enable celeborn test: https://github.com/apache/incubator-gluten/pull/5247

**Review by zhouyuan — APPROVED** [review]
👍

**Pull request merged**
