### PR TITLE
[VL] Gluten-it: Add option --scan-partitions

### PR DESCRIPTION
**Pull request by zhztheplayer**
Add options `--scan-partitions` and remove `--min-scan-partitions` which was not working for some time.

### CODE REVIEW

**Comment by FelixYBW** [comment]
What's the impact to Gluten usage?

**Comment by zhztheplayer** [comment]
> What's the impact to Gluten usage?

No impact. It just fixes a broken functionality that was not used by Gluten CI.

**Review by zhouyuan — APPROVED** [review]

**Comment by PHILO-HE** [comment]
@zhztheplayer, uniffle test failed. Is the failure relevant to this pr?
https://github.com/apache/incubator-gluten/actions/runs/9360339717/job/25767147453

**Comment by zhztheplayer** [comment]
> @zhztheplayer, uniffle test failed. Is the failure related to this pr? https://github.com/apache/incubator-gluten/actions/runs/9360339717/job/25767147453

It appears to be my mistake missing Uniffle's CI result when merging this. Thank you for helping figure out. 

https://github.com/apache/incubator-gluten/pull/5986

**Pull request merged**
