### PR TITLE
[GLUTEN-8206][VL] Support collect_set in window

### PR DESCRIPTION
**Pull request by WangGuangxin**
## What changes were proposed in this pull request?

Support collect_set in window, after 

(Fixes: \#8206)

## How was this patch tested?

Add new tests

### CODE REVIEW

**Comment by WangGuangxin** [comment]
I think collect_set has been supported in window operator after https://github.com/facebookincubator/velox/pull/10038. 

@PHILO-HE @liujiayi771

**Comment by liujiayi771** [comment]
LGTM, thanks.

**Review by liujiayi771 — APPROVED** [review]

**Comment by FelixYBW** [comment]
@zhli1142015

**Review by zhli1142015 — APPROVED** [review]
LGTM, thanks

**Pull request merged**
