### PR TITLE
DNM: [VL] Debug hash-join regression

### PR DESCRIPTION
**Pull request by zhztheplayer**
https://github.com/zhztheplayer/velox/tree/debug-joinreg

### CODE REVIEW

**Comment by zhztheplayer** [comment]
> ===== Performance report for TPCH SF2000 with Velox backend, for reference only ====
> 
> query	log/native_5401_time.csv	log/native_master_04_14_2024_0e3387255_time.csv	difference	percentage
> q1	40.53	38.08	-2.454	93.95%
> q2	24.12	23.72	-0.401	98.34%
> q3	38.22	37.90	-0.320	99.16%
> q4	38.24	39.60	1.363	103.56%
> q5	69.95	71.73	1.780	102.55%
> q6	7.40	6.97	-0.437	94.10%
> q7	82.30	84.03	1.721	102.09%
> q8	85.06	84.99	-0.072	99.92%
> q9	126.13	125.91	-0.222	99.82%
> q10	47.91	44.70	-3.200	93.32%
> q11	20.50	20.27	-0.230	98.88%
> q12	26.89	27.63	0.737	102.74%
> q13	48.21	55.28	7.071	114.67%
> q14	20.30	17.73	-2.573	87.32%
> q15	29.35	31.75	2.396	108.16%
> q16	14.43	13.82	-0.603	95.82%
> q17	101.30	100.77	-0.537	99.47%
> q18	144.74	143.22	-1.518	98.95%
> q19	15.00	15.86	0.856	105.71%
> q20	28.59	28.08	-0.508	98.22%
> q21	229.26	289.28	60.017	126.18%
> q22	14.07	14.35	0.274	101.94%
> total	1252.52	1315.66	63.139	105.04%

Hi @zhli1142015 

https://github.com/facebookincubator/velox/pull/9079 caused performance regression on hash join. Would you like to have a check?

Say q21 was slowed down from 289s to 229s in the above benchmark result table.

**Comment by zhli1142015** [comment]
sure, let me check. Thanks.

**Comment by marin-ma** [comment]
cc: @FelixYBW

**Comment by zhouyuan** [comment]
@zhli1142015 
In TPC-H q21 join keys are all unique but semi/anti joins are included, so I guess we may skip your optimization in this case?

**Comment by marin-ma** [comment]
Here's the system metrics from our daily perf test. We observed that the used memory has been increased along with the performance regression.


  | application_1712857130659_0001 | application_1712943012393_0001
-- | -- | --
runtime | 1,190.90 | 1,259.21
avg %user | 64.54 | 66.94
avg %system | 19.92 | 18.52
avg %iowait | 2.03 | 1.55
avg disk util | 51.39 | 47.26
total read (G) | 1,010.10 | 857.18
total write (G) | 1,896.31 | 1,909.39
avg read bw (MB/s) | 848.52 | 682.02
avg write bw (MB/s) | 1,592.96 | 1,519.20
cached mean | 5,880.09 | 5,606.80
cached 75% | 7,821.00 | 7,396.00
cached max | 8,886.00 | 9,060.00
used mean | 1,274.06 | 1,606.05
used 75% | 1,354.00 | 1,475.00
used max | 5,177.00 | 7,208.00

**Comment by zhztheplayer** [comment]
Hi @zhli1142015 , are you still able to have a look on this?

**Comment by zhli1142015** [comment]
Hello @zhztheplayer ,
I think this issue is mentioned is because of #6789.
Here are some obsersavation from our side for the https://github.com/facebookincubator/velox/pull/9079.
It only has impact when there are duplicate rows in build side, this can be identified if hash probe output vectors > hash probe input vectors. And it would cause longer time of hash build but shorter time of hash probe. Please let me know if this is the case you observed.
BTW, most time of hash probe of the join in query 95 (1TB in our test) is spent in hash join filter. Internally we have counter for it. I think the PR may help for the case: https://github.com/facebookincubator/velox/pull/10464

image

**Comment by zhli1142015** [comment]
Thanks for sharing this, then this maybe a different case. For such case we usually collect the profile graph to see which function is the bottleneck.

**Comment by FelixYBW** [comment]
Let's close this one for now.

**Pull request closed without merging**
