### PR TITLE
[CORE] Update ColumnarShuffleManager

### PR DESCRIPTION
**Pull request by acvictor**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by acvictor** [comment]
@ulysses-you removing using  `private lazy val sortShuffleManager` instead of `private [this] lazy val sortShuffleManager` fixed the disk cleanup issue. I observed the same free disk graph before and after the change.

**Comment by acvictor** [comment]
@ulysses-you can you please review?

**Comment by ulysses-you** [comment]
> @ulysses-you removing using private lazy val sortShuffleManager instead of private [this] lazy val sortShuffleManager fixed the disk cleanup issue. 

@acvictor  Can you elaborate the reason ? why remove `[this]` fix the issue.

**Comment by acvictor** [comment]
> > @ulysses-you removing using private lazy val sortShuffleManager instead of private [this] lazy val sortShuffleManager fixed the disk cleanup issue.
> 
> @acvictor Can you elaborate the reason ? why remove `[this]` fix the issue.

I looked at Spark code but I am not 100% clear. I think object private was affecting clean up.

**Comment by acvictor** [comment]
@jackylee-ch did you observe any regressions?

**Comment by acvictor** [comment]
@ulysses-you @jackylee-ch can you please review? I have seen no regression from my testing in Azure.

**Pull request closed without merging**
