### PR TITLE
[GLUTEN-5344][VL] Add some parquet example files from parquet-mr for native read test

### PR DESCRIPTION
**Pull request by yma11**
## What changes were proposed in this pull request?

Add some parquet example files from parquet-mr for native read test. 

## How was this patch tested?

UT

### CODE REVIEW

**Comment by yma11** [comment]
@FelixYBW I firstly port the example data files from parquet-mr in velox backend test, please take a review.

**Comment by FelixYBW** [comment]
Can they pass on current Gluten?

**Comment by yma11** [comment]
> Can they pass on current Gluten?
The `test-file-with-no-column-indexes-1.parquet` can't be read by Velox so I exclude it in test for the time being. There should be a bug. Interesting thing is that some of the example files can't be read by Spark32/33/34 but can be read by Velox successfully.

**Comment by FelixYBW** [comment]
> > Can they pass on current Gluten?
> > The `test-file-with-no-column-indexes-1.parquet` can't be read by Velox so I exclude it in test for the time being. There should be a bug. Interesting thing is that some of the example files can't be read by Spark32/33/34 but can be read by Velox successfully.

Interesting! Spark should use upstream parquet-mr but needs to specify some parameters. May because of these parameters. We may remove them since not compatible with Spark.

**Comment by yma11** [comment]
> > > Can they pass on current Gluten?
> > > The `test-file-with-no-column-indexes-1.parquet` can't be read by Velox so I exclude it in test for the time being. There should be a bug. Interesting thing is that some of the example files can't be read by Spark32/33/34 but can be read by Velox successfully.
> 
> Interesting! Spark should use upstream parquet-mr but needs to specify some parameters. May because of these parameters. We may remove them since not compatible with Spark.

That file has an empty row group which isn't allowed by Spark3.2/3.3/3.4. But it can be read by Spark 3.5. So I keep it and limit the test on Spark 3.5 version for a broader coverage.

**Comment by yma11** [comment]
@FelixYBW okay to merge this PR?

**Review by FelixYBW — APPROVED** [review]

**Comment by FelixYBW** [comment]
> @FelixYBW okay to merge this PR?

Yes, let's merge it

**Pull request merged**
