### PR TITLE
[GLUTEN-4899][VL]Fix 3.5 build issue with -Pspark-ut 

### PR DESCRIPTION
**Pull request by ayushi-agarwal**
## What changes were proposed in this pull request?

This change will fix the spark 3.5 build issue with -Pspark-ut
(Fixes: \#4899)

## How was this patch tested?

Built locally

### CODE REVIEW

**Comment by ayushi-agarwal** [comment]
@zhztheplayer @JkSelf Could you please review

**Comment by ayushi-agarwal** [comment]
@zhli1142015 Could you please review

**Review by zhztheplayer — APPROVED** [review]
Thanks for helping! And sorry for late response.

**Comment by ayushi-agarwal** [comment]
> Thanks for helping! And sorry for late response.

Thanks for reviewing.

**Review by zhli1142015 — APPROVED** [review]
LGTM.

**Comment by zhztheplayer** [comment]
@ayushi-agarwal Hi Ayushi, would you like to check the CI error ? https://github.com/apache/incubator-gluten/actions/runs/8294296666/job/22771675788?pr=4975 

Looks like it might be related to the change?

**Comment by ayushi-agarwal** [comment]
> @ayushi-agarwal Hi Ayushi, would you like to check the CI error ? https://github.com/apache/incubator-gluten/actions/runs/8294296666/job/22771675788?pr=4975
> 
> Is it related to the change? Although by looking into the code it doesn' seem to be...

@zhztheplayer The CI error is not related to my change. I see in the logs that the build succeeded but later process exited with no such file or directory. Seems some platform issue.

[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:28 min
[INFO] Finished at: 2024-03-18T08:18:26Z


+ mkdir -p /opt/gluten/dev/../package/target/thirdparty-lib
+ [[ centos == \u\b\u\n\t\u ]]
+ [[ centos == \p\o\p ]]
+ '[' centos == centos ']'
+ '[' 8 == 8 ']'
+ process_setup_centos_8
+ cp /usr/lib64/libre2.so.0 /usr/lib64/libdouble-conversion.so.3 /usr/lib64/libgflags.so.2.2 /usr/lib64/libglog.so.0 /usr/lib64/libevent-2.1.so.6 /usr/lib64/libdwarf.so.1 /usr/lib64/libgsasl.so.7 /usr/lib64/libicudata.so.60 /usr/lib64/libicui18n.so.60 /usr/lib64/libicuuc.so.60 /usr/lib64/libidn.so.11 /usr/lib64/libntlm.so.0 /usr/lib64/libsodium.so /opt/gluten/dev/../package/target/thirdparty-lib/
+ cp /usr/local/lib/libhdfs3.so.1 /usr/local/lib/libboost_context.so.1.72.0 /usr/local/lib/libboost_filesystem.so.1.72.0 /usr/local/lib/libboost_program_options.so.1.72.0 /usr/local/lib/libboost_regex.so.1.72.0 /usr/local/lib/libboost_system.so.1.72.0 /usr/local/lib/libboost_thread.so.1.72.0 /usr/local/lib/libprotobuf.so.32 /opt/gluten/dev/../package/target/thirdparty-lib/
cp: cannot stat '/usr/local/lib/libboost_context.so.1.72.0': No such file or directory
cp: cannot stat '/usr/local/lib/libboost_filesystem.so.1.72.0': No such file or directory
cp: cannot stat '/usr/local/lib/libboost_program_options.so.1.72.0': No such file or directory
cp: cannot stat '/usr/local/lib/libboost_regex.so.1.72.0': No such file or directory
cp: cannot stat '/usr/local/lib/libboost_system.so.1.72.0': No such file or directory
cp: cannot stat '/usr/local/lib/libboost_thread.so.1.72.0': No such file or directory
Error: Process completed with exit code 1.

**Pull request merged**
