### PR TITLE
[GLUTEN-6569][FOLLOWUP][VL] Delete unnecessary gcc9 enable of package script

### PR DESCRIPTION
**Pull request by wForget**
## What changes were proposed in this pull request?

Address https://github.com/apache/incubator-gluten/pull/6569#issuecomment-2268061246

## How was this patch tested?

`Velox backend weekly job` GA

### CODE REVIEW

**Comment by PHILO-HE** [comment]
@wForget, could you add some code (e.g., echo something) in velox_weekly.yml? It's just for triggering the job for verification and will be reverted before merging. Thanks!

**Comment by wForget** [comment]
> @wForget, could you add some code (e.g., echo something) in velox_weekly.yml? It's just for triggering the job for verification and will be reverted before merging. Thanks!

Good way, I will try to check this.

**Comment by PHILO-HE** [comment]
@wForget, CI has passed. Please revert the test code. Then, I will merge the pr. Thanks!

**Comment by wForget** [comment]
> @wForget, CI has passed. Please revert the test code. Then, I will merge the pr. Thanks!

Reverted the test code,

**Review by PHILO-HE — APPROVED** [review]

**Pull request merged**
