### PR TITLE
[GLUTEN-7495][BUILD] Fix macOS does not support version-script

### PR DESCRIPTION
**Pull request by zml1206**
## What changes were proposed in this pull request?

Fixes: \#7495

## How was this patch tested?

Local build test.

### CODE REVIEW

**Comment by zml1206** [comment]
cc @PHILO-HE Thank you.

**Comment by PHILO-HE** [comment]
@zml1206, not directly related to your issue. I think this check condition should be replaced by your proposed one: https://github.com/apache/incubator-gluten/blob/main/cpp/velox/CMakeLists.txt#L226. Could you help fix it here?

**Comment by zml1206** [comment]
> @zml1206, not directly related to your issue. I think this check condition should be replaced by your proposed one: https://github.com/apache/incubator-gluten/blob/main/cpp/velox/CMakeLists.txt#L226. Could you help fix it here?

CI failed seem related with replace it? @PHILO-HE

**Comment by PHILO-HE** [comment]
@zml1206, it's strange. Please revert that change. I will investigate this issue. Thanks!

**Review by PHILO-HE — APPROVED** [review]
Thanks for your fix!

**Pull request merged**
