### PR TITLE
[VL] Support array transform function

### PR DESCRIPTION
**Pull request by Yohahaha**
## What changes were proposed in this pull request?

Array transform does not support the usage that lambda function contains index variable for now.

### CODE REVIEW

**Comment by Yohahaha** [comment]
@PHILO-HE would you help take a look? thank you!

**Comment by Yohahaha** [comment]
@liujiayi771 please help take a look, thank you!

**Review by PHILO-HE — COMMENTED** [review]
Sorry for late response due to my time off in the past a few days.

The implementation looks good! I note Spark's `HigherOrderFunctionsSuite` has some tests for this function, but the suite is not covered by Gluten test. Maybe, better to enable the relevant UT?

**Comment by Yohahaha** [comment]
> Sorry for late response due to my time off in the past a few days.
> 
> The implementation looks good! I note Spark's `HigherOrderFunctionsSuite` has some tests for this function, but the suite is not covered by Gluten test. Maybe, better to enable the relevant UT?

ok, I will try enable that suite in following PR.

**Review by PHILO-HE — APPROVED** [review]
Thanks for your work!

**Pull request merged**
