### PR TITLE
[VL] Fix clang-format version

### PR DESCRIPTION
**Pull request by PHILO-HE**
~clang-format-12 is recommended to use according to Gluten doc, but the version used by CI is 15.
See:
https://github.com/apache/incubator-gluten/blob/main/dev/formatcppcode.sh~

Fix inconsistency in script and doc.

### CODE REVIEW

**Comment by PHILO-HE** [comment]
@yma11, could you take a look? Thanks!

**Comment by yma11** [comment]
What's the difference between `12` and `15`? `15` is used as consistent with CH backend.

**Comment by PHILO-HE** [comment]
> What's the difference between `12` and `15`? `15` is used as consistent with CH backend.

Certainly, there are some differences between 12 and 15. It's better to use one uniform version. I think either 12 or 15 is acceptable. If 15 is used, format script and doc needs to be fixed.

@liuneng1994, is there any reason for using 15 for CH cpp code?

**Comment by baibaichen** [comment]
> clang-format-12 is recommended to use, but the version used by CI is 15.

why use `12`?

**Comment by PHILO-HE** [comment]
> > clang-format-12 is recommended to use, but the version used by CI is 15.
> 
> why use `12`?

No strong reason. Just note a gluten velox doc recommends to use 12, but CI uses 15. Maybe, we can uniformly use 15. I will fix the inconsistency.

**Comment by liuneng1994** [comment]
> > What's the difference between `12` and `15`? `15` is used as consistent with CH backend.
> 
> Certainly, there are some differences between 12 and 15. It's better to use one uniform version. I think either 12 or 15 is acceptable. If 15 is used, format script and doc needs to be fixed.
> 
> @liuneng1994, is there any reason for using 15 for CH cpp code?

There is no special reason. CH initially used clang-format-15.

**Review by yma11 — APPROVED** [review]
nit: update the PR description for new change.

**Pull request merged**
