### PR TITLE
[GLUTEN-5016][CH] Fix exchange fallback in simple aggregation sql if spark.gluten.sql.columnar.preferColumnar=false

### PR DESCRIPTION
**Pull request by lwz9103**
## What changes were proposed in this pull request?

(Fixes: \#5016)

## How was this patch tested?

unit tests

### CODE REVIEW

**Comment by zhztheplayer** [comment]
I'll have a check to see if we can solve the issue without reverting. The change was important somehow. Thanks.

**Review by zhztheplayer — APPROVED** [review]
Thanks!

**Review by baibaichen — APPROVED** [review]
LGTM

**Comment by zhouyuan** [comment]
@zhztheplayer @baibaichen  do we still need this "preferColumnar" rule? can we remove this feature?

Thanks,
-yuan

**Comment by zhztheplayer** [comment]
Verified locally with Celeborn 0.4.0.

**Pull request merged**
