### PR TITLE
[GLUTEN-8257][CORE] Make IDEA support IssueNavigationLink

### PR DESCRIPTION
**Pull request by merrily01**
## What changes were proposed in this pull request?

Make IDEA support IssueNavigationLink.

(Fixes: \#8257)

## How was this patch tested?

Manual test.

Before:

image

After:

image

### CODE REVIEW

**Comment by PHILO-HE** [comment]
@merrily01, could you clarify how this window is opened? It's just for checking commit history? Seems `Annotate` is more useful to see historical commits for some file. And the IDE already supports jumping to the commit link.

**Comment by Yohahaha** [comment]
> @merrily01, could you clarify how this window is opened? It's just for checking commit history? Seems `Annotate` is more useful to see historical commits for some file. And the IDE already supports jumping to the commit link.

sadly, IDE does not support jumping to the commit link for now.

**Review by Yohahaha — APPROVED** [review]
👍 very helpful improvement

**Comment by zhztheplayer** [comment]
@merrily01

The feature looks great. Though will this change create conflict between repo's and user's `vcx.xml` files?

**Comment by Yohahaha** [comment]
maybe we should use a new doc to let user integrate to their IDEA.

**Review by zhztheplayer — APPROVED** [review]
Thank you for the contribution!

**Pull request merged**
