### PR TITLE
[GLUTEN-6535] Make helper scripts executable

### PR DESCRIPTION
**Pull request by xumingming**
(Fixes: \#6535)

### CODE REVIEW

**Comment by FelixYBW** [comment]
@zhouyuan any specific reason we didn't make them executable?

**Review by PHILO-HE — APPROVED** [review]
I think we should make them executable. Thanks!

**Comment by zhouyuan** [comment]
@FelixYBW missed this patch - Some of us are not using the standard "bash" but `zsh` so I usually prefer to directly call `bash script` to ensure the behavior is correct, but for this patch it should be no difference. 

thanks, -yuan

**Comment by FelixYBW** [comment]
Thank you. Let's keep it executable since it's merged.

**Pull request merged**
