### PR TITLE
[GLUTEN-4942][VL] Adding arrow port in VCPKG

### PR DESCRIPTION
**Pull request by zhouyuan**
## What changes were proposed in this pull request?

this patch adds arrow port in vcpkg list
also restore the change in package-vcpkg.sh 

## How was this patch tested?

local verified

### CODE REVIEW

**Comment by FelixYBW** [comment]
@zhouyuan how far we can move to static build as default?

**Comment by zhouyuan** [comment]
@FelixYBW 
Spark UT is working on static building now. https://github.com/apache/incubator-gluten/pull/5906
We may need extra 2-3 patches for 1) allow Velox to use external arrow build 2) improve the library loading code path to work on both static and dynamic build, as in static build no libarrow.so/libparquet.so is required 3) improve GHA to cover both packaging method

CC @ulysses-you @Yohahaha

**Review by ulysses-you — APPROVED** [review]
thank you @zhouyuan

**Comment by Yohahaha** [comment]
thank you!

> how far we can move to static build as default?

static build by default is ok, but let's stay aligned on this matter: Gluten needs to support both dynamic and static, and maybe keep one build checks for dynamic link in CI is better. @zhouyuan

**Comment by zhouyuan** [comment]
> thank you!
> 
> > how far we can move to static build as default?
> 
> static build by default is ok, but let's stay aligned on this matter: Gluten needs to support both dynamic and static, and maybe keep one build checks for dynamic link in CI is better. @zhouyuan

@Yohahaha yes, I hear the inputs, will keep the dynamic packaging 

thanks
-yuan

**Pull request closed without merging**
