### PR TITLE
[VL] Daily Update Velox Version (2024_07_04)

### PR DESCRIPTION
**Pull request by GlutenPerfBot**
Upstream Velox's New Commits:

```txt
26f001441 by xiaoxmeng, Fix tsan race in cache fuzzer test (10391)
1705bde41 by xiaoxmeng, Add exchange request count metrics (10389)
02cbe7476 by Bikramjeet Vig, Fix NaN handling in comparison functions (10165)
decd91eb5 by Kevin Wilfong, Call commitNull in SimpleFunctionAdapter on exceptions (10377)
a03396845 by Kevin Wilfong, StringWriter needs to implement finalizeNull (10376)
0cb715ea3 by youxiduo, Reject duplicate sorting keys (10040)
4e39b06c7 by gaoyangxiaozhu, Add Spark raise_error function (10110)
63ccecaa2 by rui-mo, Check determinism using function name only (10241)
```

### CODE REVIEW

**Comment by marin-ma** [comment]
@ulysses-you https://github.com/facebookincubator/velox/pull/10040 2 sqls in TestOperator "window expression" failed. Do you have a patch for Gluten to fix the duplicated sorting keys issue?

**Comment by ulysses-you** [comment]
thank you @marin-ma I will take a look

**Comment by marin-ma** [comment]
Also disabled "Literal in window partition by and sort" in `GlutenSQLWindowFunctionSuite` as the query plan generates duplicated keys in SortExec before window.

**Review by marin-ma — APPROVED** [review]
CI failure is irrelevant

**Pull request merged**
