### PR TITLE
[GLUTEN-7291][DELTA] fix: push down input_file_name expression to transformer scan in delta

### PR DESCRIPTION
**Pull request by dcoliversun**
## What changes were proposed in this pull request?

This PR aims to push down input_file_name expression to transformer scan in delta.

(Fixes: \#7291)

## How was this patch tested?

Add new unit test.

### CODE REVIEW

**Comment by dcoliversun** [comment]
@yma11 could you please have a review? thanks

**Review by yma11 — APPROVED** [review]

**Comment by felipepessoto** [comment]
@yma11, I didn't get what the unit test is doing, it is not using the input_file_name. Could you help me understand?

**Comment by yma11** [comment]
> @yma11, I didn't get what the unit test is doing, it is not using the input_file_name. Could you help me understand?

@dcoliversun can you help explain? I guess `input_file_name` is kind of from analyzed plan.

**Comment by dcoliversun** [comment]
@yma11 Thanks for ping me and you are right.

@felipepessoto Test sql fails without this commit, you could confirm it with relative issue. Delta needs file name when overwrite and Apache Spark use input_file_name to stash it. But transformer node between project and scan will return an empty string.
https://github.com/apache/incubator-gluten/blob/a07a5de3ae45a5e942824623919a49cb33d1b825/gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/PushDownInputFileExpression.scala#L28-L40

**Comment by felipepessoto** [comment]
Got it. So it means input_file_name is now supported by Gluten? I was using a custom Delta version where I replaced input_file_name by _metadata.file_path, I think I can revert my internal change.

**Comment by dcoliversun** [comment]
@felipepessoto yes, `input_file_name` is supported by Apache Gluten. I recommend using this feature. If there are any issues, feel free to open an issue for discussion.

**Pull request merged**
