### PR TITLE
[GLUTEN-5982][VL] Allow replacing installed minio package in 1.1.1 branch

### PR DESCRIPTION
**Pull request by deepashreeraghu**
## What changes were proposed in this pull request?

Allowing replace of minio package for branch 1.1.1

Fixes: https://github.com/apache/incubator-gluten/issues/5982

## How was this patch tested?

I ran a build with this fix and now it proceeds further and does not fail at rpm -i minio step.

### CODE REVIEW

**Comment by PHILO-HE** [comment]
@deepashreeraghu, could you change the target to main branch? There will be no more release in 1.1 branch.

**Comment by FelixYBW** [comment]
It's an environment issue. It's actually not only minio, but all the dependency libraries which causes version conflict.

So we shouldn't put it in get_velox.sh. Current recommendation is to build Gluten on a clean OS or docker. Otherwise there will be plenty of issues. So let's put the solution in issue.

@PHILO-HE

**Comment by PHILO-HE** [comment]
> It's an environment issue. It's actually not only minio, but all the dependency libraries which causes version conflict.
> 
> So we shouldn't put it in get_velox.sh. Current recommendation is to build Gluten on a clean OS or docker. Otherwise there will be plenty of issues. So let's put the solution in issue.
> 
> @PHILO-HE

@FelixYBW, yes, all other libs installed similarly should also have this potential issue.

**Comment by FelixYBW** [comment]
> 
> @FelixYBW, yes, all other libs installed similarly should also have this potential issue.

@deepashreeraghu can you put the error message and the solution in the issue? Looks it's not a good idea to solve the conflict in get_velox.sh. We should keep the script as simple as possible because we need to maintain it during daily velox rebase.

**Comment by deepashreeraghu** [comment]
Thanks for your response. 
I did start with a clean image to build. But while building I hit into some failures and then I retried the build locally ( to find what was the build issue actually) That retry fails even before it reaches the actual failure because it has minio on it already. 
I did not face the same trouble with other packages. Hence requested this Pull request so that builds can go through fine when being retried.

**Comment by deepashreeraghu** [comment]
Also, I am building on 1.1.1 because I wanted S3 support which is not available in the released jar. 
But, this branch does have a lot of other goodness in it and hence I opted for this branch and trying a dev build.

**Comment by deepashreeraghu** [comment]
In the main branch the same fix is already present.

**Comment by deepashreeraghu** [comment]
Since the fix will get into Velox as part of the PR - https://github.com/facebookincubator/velox/pull/10044. 
Closing this PR.

**Pull request closed without merging**
