### PR TITLE
[GLUTEN-5341][VL][Part 3] Fix and enable some uts of spark 3.5

### PR DESCRIPTION
**Pull request by gaoyangxiaozhu**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: https://github.com/apache/incubator-gluten/issues/5341)

GlutenParquetCompressionCodecPrecedenceSuite
GlutenParquetV1QuerySuite
GlutenParquetV2QuerySuite
GlutenJsonReadSchemaSuite
GlutenCoalesceShufflePartitionsSuite
GlutenInsertSuite
GlutenPartitionedWriteSuite
GlutenCachedTableSuite

## How was this patch tested?

manually test

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by yma11** [comment]
can you help mark the failures you fixed in the issue?

**Comment by gaoyangxiaozhu** [comment]
> can you help mark the failures you fixed in the issue?

hey @yma11 you mean mark in the list of the issue https://github.com/apache/incubator-gluten/issues/5341 ?

**Comment by yma11** [comment]
Yes. I'm not sure whether you can edit it, can you have a try?

**Comment by gaoyangxiaozhu** [comment]
> Yes. I'm not sure whether you can edit it, can you have a try?

actually before i already tried and i dont have permission to edit it, tried now still can't

**Comment by gaoyangxiaozhu** [comment]
> > Yes. I'm not sure whether you can edit it, can you have a try?
> 
> actually before i already tried and i dont have permission to edit it, tried now still can't

I can share all lists i have fixed to you, so you can help mark if it is ok ?

**Comment by yma11** [comment]
> > > Yes. I'm not sure whether you can edit it, can you have a try?
> > 
> > 
> > actually before i already tried and i dont have permission to edit it, tried now still can't
> 
> I can share all lists i have fixed to you, so you can help mark if it is ok ?

Yes.  You can add comments in the issue and I update the list. Thanks!

**Review by zhouyuan — APPROVED** [review]

**Pull request merged**
