### PR TITLE
[VL] Upgrade simdjson to  3.9.3 in vcpkg build

### PR DESCRIPTION
**Pull request by PHILO-HE**
## What changes were proposed in this pull request?

See velox commit:
https://github.com/facebookincubator/velox/commit/f9ae45acbfe2ae742c46bcb39f77ef3824f95c84

## How was this patch tested?

CI build.

### CODE REVIEW

**Review by zhouyuan — DISMISSED** [review]
👍

**Comment by PHILO-HE** [comment]
Just created a velox pr https://github.com/facebookincubator/velox/pull/9997 to fix the below issue (vcpkg installed simdjson cannot be used by velox, but velox still builds it from source):
```
-- Setting simdjson source to AUTO
2024-05-31T08:52:10.0849360Z CMake Warning at /__w/incubator-gluten/incubator-gluten/dev/vcpkg/.vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
2024-05-31T08:52:10.0850312Z   Could not find a configuration file for package "simdjson" that is
2024-05-31T08:52:10.0851050Z   compatible with requested version "3.8.0".
2024-05-31T08:52:10.0851548Z 
2024-05-31T08:52:10.0851888Z   The following configuration files were considered but not accepted:
2024-05-31T08:52:10.0852654Z 
2024-05-31T08:52:10.0853386Z     /__w/incubator-gluten/incubator-gluten/dev/vcpkg/vcpkg_installed/x64-linux-avx/share/simdjson/simdjson-config.cmake, version: 3.9.3
2024-05-31T08:52:10.0854100Z 
2024-05-31T08:52:10.0854222Z Call Stack (most recent call first):
2024-05-31T08:52:10.0854613Z   CMake/ResolveDependency.cmake:70 (find_package)
2024-05-31T08:52:10.0855048Z   CMakeLists.txt:451 (resolve_dependency)
```

**Comment by FelixYBW** [comment]
@PHILO-HE Can you take this oppotunity to do a perf test of json parse? Masha said there is huge perf gain. Let's confirm from Gluten.

**Comment by PHILO-HE** [comment]
> @PHILO-HE Can you take this oppotunity to do a perf test of json parse? Masha said there is huge perf gain. Let's confirm from Gluten.

@FelixYBW, I just did a small benchmark test with Spark. Velox with simdjson can bring 3x perf. gain, compared with vanilla spark. Simdjson's upgrading to version 3.93 brings 10% perf. gain, compared with the old simdjson version.

**Comment by PHILO-HE** [comment]
This pr is ready to merge. The above warning only requires velox code change to fix.

**Review by zhouyuan — APPROVED** [review]

**Pull request merged**
